// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/sequenzy/sequenzy-go/internal"
	big "math/big"
	time "time"
)

var (
	addSubscribersListsRequestFieldListID            = big.NewInt(1 << 0)
	addSubscribersListsRequestFieldDuplicateStrategy = big.NewInt(1 << 1)
	addSubscribersListsRequestFieldEmails            = big.NewInt(1 << 2)
	addSubscribersListsRequestFieldEnrollInSequences = big.NewInt(1 << 3)
	addSubscribersListsRequestFieldOptInMode         = big.NewInt(1 << 4)
)

type AddSubscribersListsRequest struct {
	// Subscriber list ID.
	ListID            string                                       `json:"-" url:"-"`
	DuplicateStrategy *AddSubscribersListsRequestDuplicateStrategy `json:"duplicateStrategy,omitempty" url:"-"`
	// Up to 500 email addresses per request.
	Emails            []string                             `json:"emails" url:"-"`
	EnrollInSequences *bool                                `json:"enrollInSequences,omitempty" url:"-"`
	OptInMode         *AddSubscribersListsRequestOptInMode `json:"optInMode,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddSubscribersListsRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetListID sets the ListID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsRequest) SetListID(listID string) {
	a.ListID = listID
	a.require(addSubscribersListsRequestFieldListID)
}

// SetDuplicateStrategy sets the DuplicateStrategy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsRequest) SetDuplicateStrategy(duplicateStrategy *AddSubscribersListsRequestDuplicateStrategy) {
	a.DuplicateStrategy = duplicateStrategy
	a.require(addSubscribersListsRequestFieldDuplicateStrategy)
}

// SetEmails sets the Emails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsRequest) SetEmails(emails []string) {
	a.Emails = emails
	a.require(addSubscribersListsRequestFieldEmails)
}

// SetEnrollInSequences sets the EnrollInSequences field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsRequest) SetEnrollInSequences(enrollInSequences *bool) {
	a.EnrollInSequences = enrollInSequences
	a.require(addSubscribersListsRequestFieldEnrollInSequences)
}

// SetOptInMode sets the OptInMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsRequest) SetOptInMode(optInMode *AddSubscribersListsRequestOptInMode) {
	a.OptInMode = optInMode
	a.require(addSubscribersListsRequestFieldOptInMode)
}

func (a *AddSubscribersListsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AddSubscribersListsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AddSubscribersListsRequest(body)
	return nil
}

func (a *AddSubscribersListsRequest) MarshalJSON() ([]byte, error) {
	type embed AddSubscribersListsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createListsRequestFieldDescription = big.NewInt(1 << 0)
	createListsRequestFieldIsPrivate   = big.NewInt(1 << 1)
	createListsRequestFieldName        = big.NewInt(1 << 2)
)

type CreateListsRequest struct {
	// Optional internal workspace metadata. Never shown in hosted or embedded subscriber preferences.
	Description *string `json:"description,omitempty" url:"-"`
	// Set to true to keep the list internal and omit it from individual controls on the hosted subscriber email preferences/unsubscribe page. Public lists expose only their name on that page; descriptions remain internal. List privacy does not override a subscriber's global unsubscribe. Defaults to false when omitted.
	IsPrivate *bool  `json:"isPrivate,omitempty" url:"-"`
	Name      string `json:"name" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateListsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateListsRequest) SetDescription(description *string) {
	c.Description = description
	c.require(createListsRequestFieldDescription)
}

// SetIsPrivate sets the IsPrivate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateListsRequest) SetIsPrivate(isPrivate *bool) {
	c.IsPrivate = isPrivate
	c.require(createListsRequestFieldIsPrivate)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateListsRequest) SetName(name string) {
	c.Name = name
	c.require(createListsRequestFieldName)
}

func (c *CreateListsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateListsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateListsRequest(body)
	return nil
}

func (c *CreateListsRequest) MarshalJSON() ([]byte, error) {
	type embed CreateListsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteListsRequestFieldListID = big.NewInt(1 << 0)
)

type DeleteListsRequest struct {
	// Subscriber list ID.
	ListID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteListsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetListID sets the ListID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteListsRequest) SetListID(listID string) {
	d.ListID = listID
	d.require(deleteListsRequestFieldListID)
}

var (
	removeSubscribersListsRequestFieldListID        = big.NewInt(1 << 0)
	removeSubscribersListsRequestFieldEmails        = big.NewInt(1 << 1)
	removeSubscribersListsRequestFieldSubscriberIDs = big.NewInt(1 << 2)
)

type RemoveSubscribersListsRequest struct {
	// Subscriber list ID.
	ListID string `json:"-" url:"-"`
	// Email addresses to remove. Combined with subscriberIds, up to 500 per request.
	Emails []string `json:"emails,omitempty" url:"-"`
	// Subscriber IDs to remove. Combined with emails, up to 500 per request.
	SubscriberIDs []string `json:"subscriberIds,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RemoveSubscribersListsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetListID sets the ListID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveSubscribersListsRequest) SetListID(listID string) {
	r.ListID = listID
	r.require(removeSubscribersListsRequestFieldListID)
}

// SetEmails sets the Emails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveSubscribersListsRequest) SetEmails(emails []string) {
	r.Emails = emails
	r.require(removeSubscribersListsRequestFieldEmails)
}

// SetSubscriberIDs sets the SubscriberIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveSubscribersListsRequest) SetSubscriberIDs(subscriberIDs []string) {
	r.SubscriberIDs = subscriberIDs
	r.require(removeSubscribersListsRequestFieldSubscriberIDs)
}

func (r *RemoveSubscribersListsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RemoveSubscribersListsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RemoveSubscribersListsRequest(body)
	return nil
}

func (r *RemoveSubscribersListsRequest) MarshalJSON() ([]byte, error) {
	type embed RemoveSubscribersListsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	subscriberListFieldActiveSubscriberCount = big.NewInt(1 << 0)
	subscriberListFieldCreatedAt             = big.NewInt(1 << 1)
	subscriberListFieldDescription           = big.NewInt(1 << 2)
	subscriberListFieldID                    = big.NewInt(1 << 3)
	subscriberListFieldIsPrivate             = big.NewInt(1 << 4)
	subscriberListFieldName                  = big.NewInt(1 << 5)
	subscriberListFieldSubscriberCount       = big.NewInt(1 << 6)
)

type SubscriberList struct {
	// Current list members with status=active. May include phone-only contacts without an email address.
	ActiveSubscriberCount *int       `json:"activeSubscriberCount,omitempty" url:"activeSubscriberCount,omitempty"`
	CreatedAt             *time.Time `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	// Internal workspace metadata returned only through authenticated list-management surfaces. Never shown in hosted or embedded subscriber preferences.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	ID          *string `json:"id,omitempty" url:"id,omitempty"`
	// Whether the list is private. Private lists are omitted from the hosted subscriber email preferences/unsubscribe page and cannot be subscribed to or unsubscribed from individually there. Public lists expose only their name on that page; descriptions remain internal. List privacy does not override a subscriber's global unsubscribe.
	IsPrivate *bool   `json:"isPrivate,omitempty" url:"isPrivate,omitempty"`
	Name      *string `json:"name,omitempty" url:"name,omitempty"`
	// Current list members of any status. Memberships with unsubscribedAt set are excluded.
	SubscriberCount *int `json:"subscriberCount,omitempty" url:"subscriberCount,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscriberList) GetActiveSubscriberCount() *int {
	if s == nil {
		return nil
	}
	return s.ActiveSubscriberCount
}

func (s *SubscriberList) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *SubscriberList) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *SubscriberList) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SubscriberList) GetIsPrivate() *bool {
	if s == nil {
		return nil
	}
	return s.IsPrivate
}

func (s *SubscriberList) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SubscriberList) GetSubscriberCount() *int {
	if s == nil {
		return nil
	}
	return s.SubscriberCount
}

func (s *SubscriberList) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscriberList) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetActiveSubscriberCount sets the ActiveSubscriberCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscriberList) SetActiveSubscriberCount(activeSubscriberCount *int) {
	s.ActiveSubscriberCount = activeSubscriberCount
	s.require(subscriberListFieldActiveSubscriberCount)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscriberList) SetCreatedAt(createdAt *time.Time) {
	s.CreatedAt = createdAt
	s.require(subscriberListFieldCreatedAt)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscriberList) SetDescription(description *string) {
	s.Description = description
	s.require(subscriberListFieldDescription)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscriberList) SetID(id *string) {
	s.ID = id
	s.require(subscriberListFieldID)
}

// SetIsPrivate sets the IsPrivate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscriberList) SetIsPrivate(isPrivate *bool) {
	s.IsPrivate = isPrivate
	s.require(subscriberListFieldIsPrivate)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscriberList) SetName(name *string) {
	s.Name = name
	s.require(subscriberListFieldName)
}

// SetSubscriberCount sets the SubscriberCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscriberList) SetSubscriberCount(subscriberCount *int) {
	s.SubscriberCount = subscriberCount
	s.require(subscriberListFieldSubscriberCount)
}

func (s *SubscriberList) UnmarshalJSON(data []byte) error {
	type embed SubscriberList
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SubscriberList(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscriberList) MarshalJSON() ([]byte, error) {
	type embed SubscriberList
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
	}{
		embed:     embed(*s),
		CreatedAt: internal.NewOptionalDateTime(s.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscriberList) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type AddSubscribersListsRequestDuplicateStrategy string

const (
	AddSubscribersListsRequestDuplicateStrategySkip      AddSubscribersListsRequestDuplicateStrategy = "skip"
	AddSubscribersListsRequestDuplicateStrategyMerge     AddSubscribersListsRequestDuplicateStrategy = "merge"
	AddSubscribersListsRequestDuplicateStrategyOverwrite AddSubscribersListsRequestDuplicateStrategy = "overwrite"
)

func NewAddSubscribersListsRequestDuplicateStrategyFromString(s string) (AddSubscribersListsRequestDuplicateStrategy, error) {
	switch s {
	case "skip":
		return AddSubscribersListsRequestDuplicateStrategySkip, nil
	case "merge":
		return AddSubscribersListsRequestDuplicateStrategyMerge, nil
	case "overwrite":
		return AddSubscribersListsRequestDuplicateStrategyOverwrite, nil
	}
	var t AddSubscribersListsRequestDuplicateStrategy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddSubscribersListsRequestDuplicateStrategy) Ptr() *AddSubscribersListsRequestDuplicateStrategy {
	return &a
}

type AddSubscribersListsRequestOptInMode string

const (
	AddSubscribersListsRequestOptInModeDefault     AddSubscribersListsRequestOptInMode = "default"
	AddSubscribersListsRequestOptInModeConfirmed   AddSubscribersListsRequestOptInMode = "confirmed"
	AddSubscribersListsRequestOptInModeDoubleOptIn AddSubscribersListsRequestOptInMode = "double_opt_in"
)

func NewAddSubscribersListsRequestOptInModeFromString(s string) (AddSubscribersListsRequestOptInMode, error) {
	switch s {
	case "default":
		return AddSubscribersListsRequestOptInModeDefault, nil
	case "confirmed":
		return AddSubscribersListsRequestOptInModeConfirmed, nil
	case "double_opt_in":
		return AddSubscribersListsRequestOptInModeDoubleOptIn, nil
	}
	var t AddSubscribersListsRequestOptInMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddSubscribersListsRequestOptInMode) Ptr() *AddSubscribersListsRequestOptInMode {
	return &a
}

var (
	addSubscribersListsResponseFieldAddedToList         = big.NewInt(1 << 0)
	addSubscribersListsResponseFieldCreated             = big.NewInt(1 << 1)
	addSubscribersListsResponseFieldDuplicateInputCount = big.NewInt(1 << 2)
	addSubscribersListsResponseFieldFailed              = big.NewInt(1 << 3)
	addSubscribersListsResponseFieldIgnoredBlankCount   = big.NewInt(1 << 4)
	addSubscribersListsResponseFieldListID              = big.NewInt(1 << 5)
	addSubscribersListsResponseFieldProcessed           = big.NewInt(1 << 6)
	addSubscribersListsResponseFieldResults             = big.NewInt(1 << 7)
	addSubscribersListsResponseFieldSkipped             = big.NewInt(1 << 8)
	addSubscribersListsResponseFieldSuccess             = big.NewInt(1 << 9)
	addSubscribersListsResponseFieldTotal               = big.NewInt(1 << 10)
	addSubscribersListsResponseFieldUpdated             = big.NewInt(1 << 11)
)

type AddSubscribersListsResponse struct {
	AddedToList         *int                                      `json:"addedToList,omitempty" url:"addedToList,omitempty"`
	Created             *int                                      `json:"created,omitempty" url:"created,omitempty"`
	DuplicateInputCount *int                                      `json:"duplicateInputCount,omitempty" url:"duplicateInputCount,omitempty"`
	Failed              *int                                      `json:"failed,omitempty" url:"failed,omitempty"`
	IgnoredBlankCount   *int                                      `json:"ignoredBlankCount,omitempty" url:"ignoredBlankCount,omitempty"`
	ListID              *string                                   `json:"listId,omitempty" url:"listId,omitempty"`
	Processed           *int                                      `json:"processed,omitempty" url:"processed,omitempty"`
	Results             []*AddSubscribersListsResponseResultsItem `json:"results,omitempty" url:"results,omitempty"`
	Skipped             *int                                      `json:"skipped,omitempty" url:"skipped,omitempty"`
	Success             *bool                                     `json:"success,omitempty" url:"success,omitempty"`
	Total               *int                                      `json:"total,omitempty" url:"total,omitempty"`
	Updated             *int                                      `json:"updated,omitempty" url:"updated,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddSubscribersListsResponse) GetAddedToList() *int {
	if a == nil {
		return nil
	}
	return a.AddedToList
}

func (a *AddSubscribersListsResponse) GetCreated() *int {
	if a == nil {
		return nil
	}
	return a.Created
}

func (a *AddSubscribersListsResponse) GetDuplicateInputCount() *int {
	if a == nil {
		return nil
	}
	return a.DuplicateInputCount
}

func (a *AddSubscribersListsResponse) GetFailed() *int {
	if a == nil {
		return nil
	}
	return a.Failed
}

func (a *AddSubscribersListsResponse) GetIgnoredBlankCount() *int {
	if a == nil {
		return nil
	}
	return a.IgnoredBlankCount
}

func (a *AddSubscribersListsResponse) GetListID() *string {
	if a == nil {
		return nil
	}
	return a.ListID
}

func (a *AddSubscribersListsResponse) GetProcessed() *int {
	if a == nil {
		return nil
	}
	return a.Processed
}

func (a *AddSubscribersListsResponse) GetResults() []*AddSubscribersListsResponseResultsItem {
	if a == nil {
		return nil
	}
	return a.Results
}

func (a *AddSubscribersListsResponse) GetSkipped() *int {
	if a == nil {
		return nil
	}
	return a.Skipped
}

func (a *AddSubscribersListsResponse) GetSuccess() *bool {
	if a == nil {
		return nil
	}
	return a.Success
}

func (a *AddSubscribersListsResponse) GetTotal() *int {
	if a == nil {
		return nil
	}
	return a.Total
}

func (a *AddSubscribersListsResponse) GetUpdated() *int {
	if a == nil {
		return nil
	}
	return a.Updated
}

func (a *AddSubscribersListsResponse) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AddSubscribersListsResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAddedToList sets the AddedToList field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetAddedToList(addedToList *int) {
	a.AddedToList = addedToList
	a.require(addSubscribersListsResponseFieldAddedToList)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetCreated(created *int) {
	a.Created = created
	a.require(addSubscribersListsResponseFieldCreated)
}

// SetDuplicateInputCount sets the DuplicateInputCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetDuplicateInputCount(duplicateInputCount *int) {
	a.DuplicateInputCount = duplicateInputCount
	a.require(addSubscribersListsResponseFieldDuplicateInputCount)
}

// SetFailed sets the Failed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetFailed(failed *int) {
	a.Failed = failed
	a.require(addSubscribersListsResponseFieldFailed)
}

// SetIgnoredBlankCount sets the IgnoredBlankCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetIgnoredBlankCount(ignoredBlankCount *int) {
	a.IgnoredBlankCount = ignoredBlankCount
	a.require(addSubscribersListsResponseFieldIgnoredBlankCount)
}

// SetListID sets the ListID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetListID(listID *string) {
	a.ListID = listID
	a.require(addSubscribersListsResponseFieldListID)
}

// SetProcessed sets the Processed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetProcessed(processed *int) {
	a.Processed = processed
	a.require(addSubscribersListsResponseFieldProcessed)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetResults(results []*AddSubscribersListsResponseResultsItem) {
	a.Results = results
	a.require(addSubscribersListsResponseFieldResults)
}

// SetSkipped sets the Skipped field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetSkipped(skipped *int) {
	a.Skipped = skipped
	a.require(addSubscribersListsResponseFieldSkipped)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetSuccess(success *bool) {
	a.Success = success
	a.require(addSubscribersListsResponseFieldSuccess)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetTotal(total *int) {
	a.Total = total
	a.require(addSubscribersListsResponseFieldTotal)
}

// SetUpdated sets the Updated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponse) SetUpdated(updated *int) {
	a.Updated = updated
	a.require(addSubscribersListsResponseFieldUpdated)
}

func (a *AddSubscribersListsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AddSubscribersListsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddSubscribersListsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddSubscribersListsResponse) MarshalJSON() ([]byte, error) {
	type embed AddSubscribersListsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddSubscribersListsResponse) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	addSubscribersListsResponseResultsItemFieldAddedToList = big.NewInt(1 << 0)
	addSubscribersListsResponseResultsItemFieldCreated     = big.NewInt(1 << 1)
	addSubscribersListsResponseResultsItemFieldEmail       = big.NewInt(1 << 2)
	addSubscribersListsResponseResultsItemFieldError       = big.NewInt(1 << 3)
	addSubscribersListsResponseResultsItemFieldSkipped     = big.NewInt(1 << 4)
	addSubscribersListsResponseResultsItemFieldSuccess     = big.NewInt(1 << 5)
	addSubscribersListsResponseResultsItemFieldUpdated     = big.NewInt(1 << 6)
)

type AddSubscribersListsResponseResultsItem struct {
	AddedToList *bool   `json:"addedToList,omitempty" url:"addedToList,omitempty"`
	Created     *bool   `json:"created,omitempty" url:"created,omitempty"`
	Email       *string `json:"email,omitempty" url:"email,omitempty"`
	Error       *string `json:"error,omitempty" url:"error,omitempty"`
	Skipped     *bool   `json:"skipped,omitempty" url:"skipped,omitempty"`
	Success     *bool   `json:"success,omitempty" url:"success,omitempty"`
	Updated     *bool   `json:"updated,omitempty" url:"updated,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddSubscribersListsResponseResultsItem) GetAddedToList() *bool {
	if a == nil {
		return nil
	}
	return a.AddedToList
}

func (a *AddSubscribersListsResponseResultsItem) GetCreated() *bool {
	if a == nil {
		return nil
	}
	return a.Created
}

func (a *AddSubscribersListsResponseResultsItem) GetEmail() *string {
	if a == nil {
		return nil
	}
	return a.Email
}

func (a *AddSubscribersListsResponseResultsItem) GetError() *string {
	if a == nil {
		return nil
	}
	return a.Error
}

func (a *AddSubscribersListsResponseResultsItem) GetSkipped() *bool {
	if a == nil {
		return nil
	}
	return a.Skipped
}

func (a *AddSubscribersListsResponseResultsItem) GetSuccess() *bool {
	if a == nil {
		return nil
	}
	return a.Success
}

func (a *AddSubscribersListsResponseResultsItem) GetUpdated() *bool {
	if a == nil {
		return nil
	}
	return a.Updated
}

func (a *AddSubscribersListsResponseResultsItem) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AddSubscribersListsResponseResultsItem) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAddedToList sets the AddedToList field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponseResultsItem) SetAddedToList(addedToList *bool) {
	a.AddedToList = addedToList
	a.require(addSubscribersListsResponseResultsItemFieldAddedToList)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponseResultsItem) SetCreated(created *bool) {
	a.Created = created
	a.require(addSubscribersListsResponseResultsItemFieldCreated)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponseResultsItem) SetEmail(email *string) {
	a.Email = email
	a.require(addSubscribersListsResponseResultsItemFieldEmail)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponseResultsItem) SetError(error_ *string) {
	a.Error = error_
	a.require(addSubscribersListsResponseResultsItemFieldError)
}

// SetSkipped sets the Skipped field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponseResultsItem) SetSkipped(skipped *bool) {
	a.Skipped = skipped
	a.require(addSubscribersListsResponseResultsItemFieldSkipped)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponseResultsItem) SetSuccess(success *bool) {
	a.Success = success
	a.require(addSubscribersListsResponseResultsItemFieldSuccess)
}

// SetUpdated sets the Updated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddSubscribersListsResponseResultsItem) SetUpdated(updated *bool) {
	a.Updated = updated
	a.require(addSubscribersListsResponseResultsItemFieldUpdated)
}

func (a *AddSubscribersListsResponseResultsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler AddSubscribersListsResponseResultsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddSubscribersListsResponseResultsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddSubscribersListsResponseResultsItem) MarshalJSON() ([]byte, error) {
	type embed AddSubscribersListsResponseResultsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddSubscribersListsResponseResultsItem) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	createListsResponseFieldList    = big.NewInt(1 << 0)
	createListsResponseFieldSuccess = big.NewInt(1 << 1)
)

type CreateListsResponse struct {
	List    *SubscriberList `json:"list,omitempty" url:"list,omitempty"`
	Success *bool           `json:"success,omitempty" url:"success,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateListsResponse) GetList() *SubscriberList {
	if c == nil {
		return nil
	}
	return c.List
}

func (c *CreateListsResponse) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

func (c *CreateListsResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateListsResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetList sets the List field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateListsResponse) SetList(list *SubscriberList) {
	c.List = list
	c.require(createListsResponseFieldList)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateListsResponse) SetSuccess(success *bool) {
	c.Success = success
	c.require(createListsResponseFieldSuccess)
}

func (c *CreateListsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateListsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateListsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateListsResponse) MarshalJSON() ([]byte, error) {
	type embed CreateListsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateListsResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	deleteListsResponseFieldRemovedMemberships = big.NewInt(1 << 0)
	deleteListsResponseFieldSuccess            = big.NewInt(1 << 1)
)

type DeleteListsResponse struct {
	// Number of list memberships removed.
	RemovedMemberships *int  `json:"removedMemberships,omitempty" url:"removedMemberships,omitempty"`
	Success            *bool `json:"success,omitempty" url:"success,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteListsResponse) GetRemovedMemberships() *int {
	if d == nil {
		return nil
	}
	return d.RemovedMemberships
}

func (d *DeleteListsResponse) GetSuccess() *bool {
	if d == nil {
		return nil
	}
	return d.Success
}

func (d *DeleteListsResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteListsResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetRemovedMemberships sets the RemovedMemberships field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteListsResponse) SetRemovedMemberships(removedMemberships *int) {
	d.RemovedMemberships = removedMemberships
	d.require(deleteListsResponseFieldRemovedMemberships)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteListsResponse) SetSuccess(success *bool) {
	d.Success = success
	d.require(deleteListsResponseFieldSuccess)
}

func (d *DeleteListsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteListsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteListsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteListsResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteListsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteListsResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	listListsResponseFieldLists   = big.NewInt(1 << 0)
	listListsResponseFieldSuccess = big.NewInt(1 << 1)
)

type ListListsResponse struct {
	Lists   []*SubscriberList `json:"lists,omitempty" url:"lists,omitempty"`
	Success *bool             `json:"success,omitempty" url:"success,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListListsResponse) GetLists() []*SubscriberList {
	if l == nil {
		return nil
	}
	return l.Lists
}

func (l *ListListsResponse) GetSuccess() *bool {
	if l == nil {
		return nil
	}
	return l.Success
}

func (l *ListListsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListListsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLists sets the Lists field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsResponse) SetLists(lists []*SubscriberList) {
	l.Lists = lists
	l.require(listListsResponseFieldLists)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsResponse) SetSuccess(success *bool) {
	l.Success = success
	l.require(listListsResponseFieldSuccess)
}

func (l *ListListsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListListsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListListsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListListsResponse) MarshalJSON() ([]byte, error) {
	type embed ListListsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListListsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	removeSubscribersListsResponseFieldNotFound = big.NewInt(1 << 0)
	removeSubscribersListsResponseFieldRemoved  = big.NewInt(1 << 1)
	removeSubscribersListsResponseFieldSuccess  = big.NewInt(1 << 2)
)

type RemoveSubscribersListsResponse struct {
	// Emails that did not match any subscriber.
	NotFound []string `json:"notFound,omitempty" url:"notFound,omitempty"`
	// Number of list memberships removed.
	Removed *int  `json:"removed,omitempty" url:"removed,omitempty"`
	Success *bool `json:"success,omitempty" url:"success,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RemoveSubscribersListsResponse) GetNotFound() []string {
	if r == nil {
		return nil
	}
	return r.NotFound
}

func (r *RemoveSubscribersListsResponse) GetRemoved() *int {
	if r == nil {
		return nil
	}
	return r.Removed
}

func (r *RemoveSubscribersListsResponse) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *RemoveSubscribersListsResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RemoveSubscribersListsResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetNotFound sets the NotFound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveSubscribersListsResponse) SetNotFound(notFound []string) {
	r.NotFound = notFound
	r.require(removeSubscribersListsResponseFieldNotFound)
}

// SetRemoved sets the Removed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveSubscribersListsResponse) SetRemoved(removed *int) {
	r.Removed = removed
	r.require(removeSubscribersListsResponseFieldRemoved)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveSubscribersListsResponse) SetSuccess(success *bool) {
	r.Success = success
	r.require(removeSubscribersListsResponseFieldSuccess)
}

func (r *RemoveSubscribersListsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RemoveSubscribersListsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RemoveSubscribersListsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RemoveSubscribersListsResponse) MarshalJSON() ([]byte, error) {
	type embed RemoveSubscribersListsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RemoveSubscribersListsResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	updateListsResponseFieldList    = big.NewInt(1 << 0)
	updateListsResponseFieldSuccess = big.NewInt(1 << 1)
)

type UpdateListsResponse struct {
	List    *SubscriberList `json:"list,omitempty" url:"list,omitempty"`
	Success *bool           `json:"success,omitempty" url:"success,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateListsResponse) GetList() *SubscriberList {
	if u == nil {
		return nil
	}
	return u.List
}

func (u *UpdateListsResponse) GetSuccess() *bool {
	if u == nil {
		return nil
	}
	return u.Success
}

func (u *UpdateListsResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateListsResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetList sets the List field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateListsResponse) SetList(list *SubscriberList) {
	u.List = list
	u.require(updateListsResponseFieldList)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateListsResponse) SetSuccess(success *bool) {
	u.Success = success
	u.require(updateListsResponseFieldSuccess)
}

func (u *UpdateListsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateListsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateListsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateListsResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateListsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateListsResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateListsRequestFieldListID      = big.NewInt(1 << 0)
	updateListsRequestFieldDescription = big.NewInt(1 << 1)
	updateListsRequestFieldIsPrivate   = big.NewInt(1 << 2)
	updateListsRequestFieldName        = big.NewInt(1 << 3)
)

type UpdateListsRequest struct {
	// Subscriber list ID.
	ListID string `json:"-" url:"-"`
	// New internal list description. Never shown in hosted or embedded subscriber preferences. Pass null to clear it.
	Description *string `json:"description,omitempty" url:"-"`
	// Set to true to keep the list internal and omit it from individual controls on the hosted subscriber email preferences/unsubscribe page. Set to false to expose only its name on that page; descriptions remain internal. List privacy does not override a subscriber's global unsubscribe. Omit this field to leave the current visibility unchanged.
	IsPrivate *bool `json:"isPrivate,omitempty" url:"-"`
	// New list name.
	Name *string `json:"name,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateListsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetListID sets the ListID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateListsRequest) SetListID(listID string) {
	u.ListID = listID
	u.require(updateListsRequestFieldListID)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateListsRequest) SetDescription(description *string) {
	u.Description = description
	u.require(updateListsRequestFieldDescription)
}

// SetIsPrivate sets the IsPrivate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateListsRequest) SetIsPrivate(isPrivate *bool) {
	u.IsPrivate = isPrivate
	u.require(updateListsRequestFieldIsPrivate)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateListsRequest) SetName(name *string) {
	u.Name = name
	u.require(updateListsRequestFieldName)
}

func (u *UpdateListsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateListsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateListsRequest(body)
	return nil
}

func (u *UpdateListsRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateListsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
