// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersReplyProfileSummary(t *testing.T) {
	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &ReplyProfileSummary{}
		var fernTestValueCreatedAt *time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEmail", func(t *testing.T) {
		obj := &ReplyProfileSummary{}
		var fernTestValueEmail *string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &ReplyProfileSummary{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsDefault", func(t *testing.T) {
		obj := &ReplyProfileSummary{}
		var fernTestValueIsDefault *bool
		obj.SetIsDefault(fernTestValueIsDefault)
		assert.Equal(t, fernTestValueIsDefault, obj.IsDefault)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &ReplyProfileSummary{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersReplyProfileSummary(t *testing.T) {
	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		var expected *time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		obj.CreatedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreatedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReplyProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetEmail", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		var expected *string
		obj.Email = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEmail(), "getter should return the property value")
	})

	t.Run("GetEmail_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		obj.Email = nil

		// Act & Assert
		assert.Nil(t, obj.GetEmail(), "getter should return nil when property is nil")
	})

	t.Run("GetEmail_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReplyProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEmail() // Should return zero value
	})

	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		var expected *string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReplyProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetIsDefault", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		var expected *bool
		obj.IsDefault = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsDefault(), "getter should return the property value")
	})

	t.Run("GetIsDefault_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		obj.IsDefault = nil

		// Act & Assert
		assert.Nil(t, obj.GetIsDefault(), "getter should return nil when property is nil")
	})

	t.Run("GetIsDefault_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReplyProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsDefault() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReplyProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

}

func TestSettersMarkExplicitReplyProfileSummary(t *testing.T) {
	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		var fernTestValueCreatedAt *time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		var fernTestValueEmail *string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsDefault_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		var fernTestValueIsDefault *bool

		// Act
		obj.SetIsDefault(fernTestValueIsDefault)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSenderProfileSummary(t *testing.T) {
	t.Run("SetCanSend", func(t *testing.T) {
		obj := &SenderProfileSummary{}
		var fernTestValueCanSend *bool
		obj.SetCanSend(fernTestValueCanSend)
		assert.Equal(t, fernTestValueCanSend, obj.CanSend)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &SenderProfileSummary{}
		var fernTestValueCreatedAt *time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomain", func(t *testing.T) {
		obj := &SenderProfileSummary{}
		var fernTestValueDomain *string
		obj.SetDomain(fernTestValueDomain)
		assert.Equal(t, fernTestValueDomain, obj.Domain)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomainID", func(t *testing.T) {
		obj := &SenderProfileSummary{}
		var fernTestValueDomainID *string
		obj.SetDomainID(fernTestValueDomainID)
		assert.Equal(t, fernTestValueDomainID, obj.DomainID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomainStatus", func(t *testing.T) {
		obj := &SenderProfileSummary{}
		var fernTestValueDomainStatus *string
		obj.SetDomainStatus(fernTestValueDomainStatus)
		assert.Equal(t, fernTestValueDomainStatus, obj.DomainStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEmail", func(t *testing.T) {
		obj := &SenderProfileSummary{}
		var fernTestValueEmail *string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &SenderProfileSummary{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsDefault", func(t *testing.T) {
		obj := &SenderProfileSummary{}
		var fernTestValueIsDefault *bool
		obj.SetIsDefault(fernTestValueIsDefault)
		assert.Equal(t, fernTestValueIsDefault, obj.IsDefault)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &SenderProfileSummary{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSenderProfileSummary(t *testing.T) {
	t.Run("GetCanSend", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var expected *bool
		obj.CanSend = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCanSend(), "getter should return the property value")
	})

	t.Run("GetCanSend_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		obj.CanSend = nil

		// Act & Assert
		assert.Nil(t, obj.GetCanSend(), "getter should return nil when property is nil")
	})

	t.Run("GetCanSend_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCanSend() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var expected *time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		obj.CreatedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreatedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetDomain", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var expected *string
		obj.Domain = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomain(), "getter should return the property value")
	})

	t.Run("GetDomain_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		obj.Domain = nil

		// Act & Assert
		assert.Nil(t, obj.GetDomain(), "getter should return nil when property is nil")
	})

	t.Run("GetDomain_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomain() // Should return zero value
	})

	t.Run("GetDomainID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var expected *string
		obj.DomainID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomainID(), "getter should return the property value")
	})

	t.Run("GetDomainID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		obj.DomainID = nil

		// Act & Assert
		assert.Nil(t, obj.GetDomainID(), "getter should return nil when property is nil")
	})

	t.Run("GetDomainID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomainID() // Should return zero value
	})

	t.Run("GetDomainStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var expected *string
		obj.DomainStatus = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomainStatus(), "getter should return the property value")
	})

	t.Run("GetDomainStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		obj.DomainStatus = nil

		// Act & Assert
		assert.Nil(t, obj.GetDomainStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetDomainStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomainStatus() // Should return zero value
	})

	t.Run("GetEmail", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var expected *string
		obj.Email = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEmail(), "getter should return the property value")
	})

	t.Run("GetEmail_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		obj.Email = nil

		// Act & Assert
		assert.Nil(t, obj.GetEmail(), "getter should return nil when property is nil")
	})

	t.Run("GetEmail_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEmail() // Should return zero value
	})

	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var expected *string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetIsDefault", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var expected *bool
		obj.IsDefault = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsDefault(), "getter should return the property value")
	})

	t.Run("GetIsDefault_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		obj.IsDefault = nil

		// Act & Assert
		assert.Nil(t, obj.GetIsDefault(), "getter should return nil when property is nil")
	})

	t.Run("GetIsDefault_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsDefault() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

}

func TestSettersMarkExplicitSenderProfileSummary(t *testing.T) {
	t.Run("SetCanSend_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var fernTestValueCanSend *bool

		// Act
		obj.SetCanSend(fernTestValueCanSend)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var fernTestValueCreatedAt *time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var fernTestValueDomain *string

		// Act
		obj.SetDomain(fernTestValueDomain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomainID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var fernTestValueDomainID *string

		// Act
		obj.SetDomainID(fernTestValueDomainID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomainStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var fernTestValueDomainStatus *string

		// Act
		obj.SetDomainStatus(fernTestValueDomainStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var fernTestValueEmail *string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsDefault_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var fernTestValueIsDefault *bool

		// Act
		obj.SetIsDefault(fernTestValueIsDefault)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListSenderProfilesResponse(t *testing.T) {
	t.Run("SetDefaultReplyProfileID", func(t *testing.T) {
		obj := &ListSenderProfilesResponse{}
		var fernTestValueDefaultReplyProfileID *string
		obj.SetDefaultReplyProfileID(fernTestValueDefaultReplyProfileID)
		assert.Equal(t, fernTestValueDefaultReplyProfileID, obj.DefaultReplyProfileID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDefaultSenderProfileID", func(t *testing.T) {
		obj := &ListSenderProfilesResponse{}
		var fernTestValueDefaultSenderProfileID *string
		obj.SetDefaultSenderProfileID(fernTestValueDefaultSenderProfileID)
		assert.Equal(t, fernTestValueDefaultSenderProfileID, obj.DefaultSenderProfileID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetReplyProfiles", func(t *testing.T) {
		obj := &ListSenderProfilesResponse{}
		var fernTestValueReplyProfiles []*ReplyProfileSummary
		obj.SetReplyProfiles(fernTestValueReplyProfiles)
		assert.Equal(t, fernTestValueReplyProfiles, obj.ReplyProfiles)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSenderProfiles", func(t *testing.T) {
		obj := &ListSenderProfilesResponse{}
		var fernTestValueSenderProfiles []*SenderProfileSummary
		obj.SetSenderProfiles(fernTestValueSenderProfiles)
		assert.Equal(t, fernTestValueSenderProfiles, obj.SenderProfiles)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccess", func(t *testing.T) {
		obj := &ListSenderProfilesResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListSenderProfilesResponse(t *testing.T) {
	t.Run("GetDefaultReplyProfileID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		var expected *string
		obj.DefaultReplyProfileID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDefaultReplyProfileID(), "getter should return the property value")
	})

	t.Run("GetDefaultReplyProfileID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		obj.DefaultReplyProfileID = nil

		// Act & Assert
		assert.Nil(t, obj.GetDefaultReplyProfileID(), "getter should return nil when property is nil")
	})

	t.Run("GetDefaultReplyProfileID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSenderProfilesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDefaultReplyProfileID() // Should return zero value
	})

	t.Run("GetDefaultSenderProfileID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		var expected *string
		obj.DefaultSenderProfileID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDefaultSenderProfileID(), "getter should return the property value")
	})

	t.Run("GetDefaultSenderProfileID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		obj.DefaultSenderProfileID = nil

		// Act & Assert
		assert.Nil(t, obj.GetDefaultSenderProfileID(), "getter should return nil when property is nil")
	})

	t.Run("GetDefaultSenderProfileID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSenderProfilesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDefaultSenderProfileID() // Should return zero value
	})

	t.Run("GetReplyProfiles", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		var expected []*ReplyProfileSummary
		obj.ReplyProfiles = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetReplyProfiles(), "getter should return the property value")
	})

	t.Run("GetReplyProfiles_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		obj.ReplyProfiles = nil

		// Act & Assert
		assert.Nil(t, obj.GetReplyProfiles(), "getter should return nil when property is nil")
	})

	t.Run("GetReplyProfiles_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSenderProfilesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetReplyProfiles() // Should return zero value
	})

	t.Run("GetSenderProfiles", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		var expected []*SenderProfileSummary
		obj.SenderProfiles = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSenderProfiles(), "getter should return the property value")
	})

	t.Run("GetSenderProfiles_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		obj.SenderProfiles = nil

		// Act & Assert
		assert.Nil(t, obj.GetSenderProfiles(), "getter should return nil when property is nil")
	})

	t.Run("GetSenderProfiles_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSenderProfilesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSenderProfiles() // Should return zero value
	})

	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSenderProfilesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

}

func TestSettersMarkExplicitListSenderProfilesResponse(t *testing.T) {
	t.Run("SetDefaultReplyProfileID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		var fernTestValueDefaultReplyProfileID *string

		// Act
		obj.SetDefaultReplyProfileID(fernTestValueDefaultReplyProfileID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDefaultSenderProfileID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		var fernTestValueDefaultSenderProfileID *string

		// Act
		obj.SetDefaultSenderProfileID(fernTestValueDefaultSenderProfileID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetReplyProfiles_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		var fernTestValueReplyProfiles []*ReplyProfileSummary

		// Act
		obj.SetReplyProfiles(fernTestValueReplyProfiles)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSenderProfiles_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		var fernTestValueSenderProfiles []*SenderProfileSummary

		// Act
		obj.SetSenderProfiles(fernTestValueSenderProfiles)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateReplyProfileResponse(t *testing.T) {
	t.Run("SetRenamed", func(t *testing.T) {
		obj := &UpdateReplyProfileResponse{}
		var fernTestValueRenamed *bool
		obj.SetRenamed(fernTestValueRenamed)
		assert.Equal(t, fernTestValueRenamed, obj.Renamed)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetReplyProfile", func(t *testing.T) {
		obj := &UpdateReplyProfileResponse{}
		var fernTestValueReplyProfile *ReplyProfileSummary
		obj.SetReplyProfile(fernTestValueReplyProfile)
		assert.Equal(t, fernTestValueReplyProfile, obj.ReplyProfile)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccess", func(t *testing.T) {
		obj := &UpdateReplyProfileResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUpdateReplyProfileResponse(t *testing.T) {
	t.Run("GetRenamed", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileResponse{}
		var expected *bool
		obj.Renamed = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRenamed(), "getter should return the property value")
	})

	t.Run("GetRenamed_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileResponse{}
		obj.Renamed = nil

		// Act & Assert
		assert.Nil(t, obj.GetRenamed(), "getter should return nil when property is nil")
	})

	t.Run("GetRenamed_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateReplyProfileResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRenamed() // Should return zero value
	})

	t.Run("GetReplyProfile", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileResponse{}
		var expected *ReplyProfileSummary
		obj.ReplyProfile = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetReplyProfile(), "getter should return the property value")
	})

	t.Run("GetReplyProfile_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileResponse{}
		obj.ReplyProfile = nil

		// Act & Assert
		assert.Nil(t, obj.GetReplyProfile(), "getter should return nil when property is nil")
	})

	t.Run("GetReplyProfile_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateReplyProfileResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetReplyProfile() // Should return zero value
	})

	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateReplyProfileResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

}

func TestSettersMarkExplicitUpdateReplyProfileResponse(t *testing.T) {
	t.Run("SetRenamed_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileResponse{}
		var fernTestValueRenamed *bool

		// Act
		obj.SetRenamed(fernTestValueRenamed)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetReplyProfile_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileResponse{}
		var fernTestValueReplyProfile *ReplyProfileSummary

		// Act
		obj.SetReplyProfile(fernTestValueReplyProfile)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateSenderProfilesResponse(t *testing.T) {
	t.Run("SetRenamed", func(t *testing.T) {
		obj := &UpdateSenderProfilesResponse{}
		var fernTestValueRenamed *bool
		obj.SetRenamed(fernTestValueRenamed)
		assert.Equal(t, fernTestValueRenamed, obj.Renamed)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSenderProfile", func(t *testing.T) {
		obj := &UpdateSenderProfilesResponse{}
		var fernTestValueSenderProfile *SenderProfileSummary
		obj.SetSenderProfile(fernTestValueSenderProfile)
		assert.Equal(t, fernTestValueSenderProfile, obj.SenderProfile)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccess", func(t *testing.T) {
		obj := &UpdateSenderProfilesResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUpdateSenderProfilesResponse(t *testing.T) {
	t.Run("GetRenamed", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesResponse{}
		var expected *bool
		obj.Renamed = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRenamed(), "getter should return the property value")
	})

	t.Run("GetRenamed_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesResponse{}
		obj.Renamed = nil

		// Act & Assert
		assert.Nil(t, obj.GetRenamed(), "getter should return nil when property is nil")
	})

	t.Run("GetRenamed_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateSenderProfilesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRenamed() // Should return zero value
	})

	t.Run("GetSenderProfile", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesResponse{}
		var expected *SenderProfileSummary
		obj.SenderProfile = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSenderProfile(), "getter should return the property value")
	})

	t.Run("GetSenderProfile_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesResponse{}
		obj.SenderProfile = nil

		// Act & Assert
		assert.Nil(t, obj.GetSenderProfile(), "getter should return nil when property is nil")
	})

	t.Run("GetSenderProfile_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateSenderProfilesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSenderProfile() // Should return zero value
	})

	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateSenderProfilesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

}

func TestSettersMarkExplicitUpdateSenderProfilesResponse(t *testing.T) {
	t.Run("SetRenamed_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesResponse{}
		var fernTestValueRenamed *bool

		// Act
		obj.SetRenamed(fernTestValueRenamed)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSenderProfile_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesResponse{}
		var fernTestValueSenderProfile *SenderProfileSummary

		// Act
		obj.SetSenderProfile(fernTestValueSenderProfile)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateSenderProfilesRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &UpdateSenderProfilesRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &UpdateSenderProfilesRequest{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUpdateSenderProfilesRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesRequest{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateReplyProfileRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &UpdateReplyProfileRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &UpdateReplyProfileRequest{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUpdateReplyProfileRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileRequest{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingListSenderProfilesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSenderProfilesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListSenderProfilesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListSenderProfilesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListSenderProfilesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingReplyProfileSummary(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReplyProfileSummary{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ReplyProfileSummary
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ReplyProfileSummary
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ReplyProfileSummary
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingSenderProfileSummary(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SenderProfileSummary{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SenderProfileSummary
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SenderProfileSummary
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SenderProfileSummary
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUpdateReplyProfileResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateReplyProfileResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UpdateReplyProfileResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UpdateReplyProfileResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UpdateReplyProfileResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUpdateSenderProfilesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSenderProfilesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UpdateSenderProfilesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UpdateSenderProfilesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UpdateSenderProfilesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringListSenderProfilesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListSenderProfilesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSenderProfilesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringReplyProfileSummary(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ReplyProfileSummary{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReplyProfileSummary
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringSenderProfileSummary(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SenderProfileSummary{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUpdateReplyProfileResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UpdateReplyProfileResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateReplyProfileResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUpdateSenderProfilesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UpdateSenderProfilesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateSenderProfilesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesListSenderProfilesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListSenderProfilesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSenderProfilesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesReplyProfileSummary(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ReplyProfileSummary{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReplyProfileSummary
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesSenderProfileSummary(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SenderProfileSummary{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SenderProfileSummary
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUpdateReplyProfileResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UpdateReplyProfileResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateReplyProfileResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUpdateSenderProfilesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UpdateSenderProfilesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateSenderProfilesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
