// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/sequenzy/sequenzy-go/internal"
	big "math/big"
	time "time"
)

var (
	releaseNumberSmsRequestFieldNumberID = big.NewInt(1 << 0)
)

type ReleaseNumberSmsRequest struct {
	// SMS number ID from GET /sms/settings.
	NumberID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReleaseNumberSmsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetNumberID sets the NumberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleaseNumberSmsRequest) SetNumberID(numberID string) {
	r.NumberID = numberID
	r.require(releaseNumberSmsRequestFieldNumberID)
}

var (
	sendTestSmsRequestFieldBlocks       = big.NewInt(1 << 0)
	sendTestSmsRequestFieldFromNumberID = big.NewInt(1 << 1)
	sendTestSmsRequestFieldImageURLs    = big.NewInt(1 << 2)
	sendTestSmsRequestFieldText         = big.NewInt(1 << 3)
	sendTestSmsRequestFieldTo           = big.NewInt(1 << 4)
)

type SendTestSmsRequest struct {
	// SMS content blocks (text + image subset). Provide text or blocks, not both.
	Blocks []map[string]any `json:"blocks,omitempty" url:"-"`
	// Verified sending number ID from GET /sms/settings. Omit to use the oldest verified company number. An invalid explicit selection returns 400 instead of falling back.
	FromNumberID *string `json:"fromNumberId,omitempty" url:"-"`
	// Up to 2 publicly reachable image URLs sent as MMS media (US/CA only).
	ImageURLs []string `json:"imageUrls,omitempty" url:"-"`
	// Plain-text message body. Provide text or blocks, not both.
	Text *string `json:"text,omitempty" url:"-"`
	// Destination phone number in international E.164 format.
	To string `json:"to" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SendTestSmsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetBlocks sets the Blocks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendTestSmsRequest) SetBlocks(blocks []map[string]any) {
	s.Blocks = blocks
	s.require(sendTestSmsRequestFieldBlocks)
}

// SetFromNumberID sets the FromNumberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendTestSmsRequest) SetFromNumberID(fromNumberID *string) {
	s.FromNumberID = fromNumberID
	s.require(sendTestSmsRequestFieldFromNumberID)
}

// SetImageURLs sets the ImageURLs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendTestSmsRequest) SetImageURLs(imageURLs []string) {
	s.ImageURLs = imageURLs
	s.require(sendTestSmsRequestFieldImageURLs)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendTestSmsRequest) SetText(text *string) {
	s.Text = text
	s.require(sendTestSmsRequestFieldText)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendTestSmsRequest) SetTo(to string) {
	s.To = to
	s.require(sendTestSmsRequestFieldTo)
}

func (s *SendTestSmsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SendTestSmsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SendTestSmsRequest(body)
	return nil
}

func (s *SendTestSmsRequest) MarshalJSON() ([]byte, error) {
	type embed SendTestSmsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getSettingsSmsResponseFieldMessage = big.NewInt(1 << 0)
	getSettingsSmsResponseFieldSms     = big.NewInt(1 << 1)
	getSettingsSmsResponseFieldSuccess = big.NewInt(1 << 2)
)

type GetSettingsSmsResponse struct {
	Message *string                    `json:"message,omitempty" url:"message,omitempty"`
	Sms     *GetSettingsSmsResponseSms `json:"sms,omitempty" url:"sms,omitempty"`
	Success *bool                      `json:"success,omitempty" url:"success,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetSettingsSmsResponse) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetSettingsSmsResponse) GetSms() *GetSettingsSmsResponseSms {
	if g == nil {
		return nil
	}
	return g.Sms
}

func (g *GetSettingsSmsResponse) GetSuccess() *bool {
	if g == nil {
		return nil
	}
	return g.Success
}

func (g *GetSettingsSmsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetSettingsSmsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponse) SetMessage(message *string) {
	g.Message = message
	g.require(getSettingsSmsResponseFieldMessage)
}

// SetSms sets the Sms field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponse) SetSms(sms *GetSettingsSmsResponseSms) {
	g.Sms = sms
	g.require(getSettingsSmsResponseFieldSms)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponse) SetSuccess(success *bool) {
	g.Success = success
	g.require(getSettingsSmsResponseFieldSuccess)
}

func (g *GetSettingsSmsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSettingsSmsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetSettingsSmsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetSettingsSmsResponse) MarshalJSON() ([]byte, error) {
	type embed GetSettingsSmsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetSettingsSmsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getSettingsSmsResponseSmsFieldBrandPrefix    = big.NewInt(1 << 0)
	getSettingsSmsResponseSmsFieldCreditsBalance = big.NewInt(1 << 1)
	getSettingsSmsResponseSmsFieldEnabled        = big.NewInt(1 << 2)
	getSettingsSmsResponseSmsFieldNumbers        = big.NewInt(1 << 3)
	getSettingsSmsResponseSmsFieldPlanEligible   = big.NewInt(1 << 4)
	getSettingsSmsResponseSmsFieldReadyToSend    = big.NewInt(1 << 5)
)

type GetSettingsSmsResponseSms struct {
	BrandPrefix    *string                                 `json:"brandPrefix,omitempty" url:"brandPrefix,omitempty"`
	CreditsBalance *float64                                `json:"creditsBalance,omitempty" url:"creditsBalance,omitempty"`
	Enabled        *bool                                   `json:"enabled,omitempty" url:"enabled,omitempty"`
	Numbers        []*GetSettingsSmsResponseSmsNumbersItem `json:"numbers,omitempty" url:"numbers,omitempty"`
	PlanEligible   *bool                                   `json:"planEligible,omitempty" url:"planEligible,omitempty"`
	ReadyToSend    *bool                                   `json:"readyToSend,omitempty" url:"readyToSend,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetSettingsSmsResponseSms) GetBrandPrefix() *string {
	if g == nil {
		return nil
	}
	return g.BrandPrefix
}

func (g *GetSettingsSmsResponseSms) GetCreditsBalance() *float64 {
	if g == nil {
		return nil
	}
	return g.CreditsBalance
}

func (g *GetSettingsSmsResponseSms) GetEnabled() *bool {
	if g == nil {
		return nil
	}
	return g.Enabled
}

func (g *GetSettingsSmsResponseSms) GetNumbers() []*GetSettingsSmsResponseSmsNumbersItem {
	if g == nil {
		return nil
	}
	return g.Numbers
}

func (g *GetSettingsSmsResponseSms) GetPlanEligible() *bool {
	if g == nil {
		return nil
	}
	return g.PlanEligible
}

func (g *GetSettingsSmsResponseSms) GetReadyToSend() *bool {
	if g == nil {
		return nil
	}
	return g.ReadyToSend
}

func (g *GetSettingsSmsResponseSms) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetSettingsSmsResponseSms) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetBrandPrefix sets the BrandPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSms) SetBrandPrefix(brandPrefix *string) {
	g.BrandPrefix = brandPrefix
	g.require(getSettingsSmsResponseSmsFieldBrandPrefix)
}

// SetCreditsBalance sets the CreditsBalance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSms) SetCreditsBalance(creditsBalance *float64) {
	g.CreditsBalance = creditsBalance
	g.require(getSettingsSmsResponseSmsFieldCreditsBalance)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSms) SetEnabled(enabled *bool) {
	g.Enabled = enabled
	g.require(getSettingsSmsResponseSmsFieldEnabled)
}

// SetNumbers sets the Numbers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSms) SetNumbers(numbers []*GetSettingsSmsResponseSmsNumbersItem) {
	g.Numbers = numbers
	g.require(getSettingsSmsResponseSmsFieldNumbers)
}

// SetPlanEligible sets the PlanEligible field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSms) SetPlanEligible(planEligible *bool) {
	g.PlanEligible = planEligible
	g.require(getSettingsSmsResponseSmsFieldPlanEligible)
}

// SetReadyToSend sets the ReadyToSend field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSms) SetReadyToSend(readyToSend *bool) {
	g.ReadyToSend = readyToSend
	g.require(getSettingsSmsResponseSmsFieldReadyToSend)
}

func (g *GetSettingsSmsResponseSms) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSettingsSmsResponseSms
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetSettingsSmsResponseSms(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetSettingsSmsResponseSms) MarshalJSON() ([]byte, error) {
	type embed GetSettingsSmsResponseSms
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetSettingsSmsResponseSms) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getSettingsSmsResponseSmsNumbersItemFieldBrandPrefix = big.NewInt(1 << 0)
	getSettingsSmsResponseSmsNumbersItemFieldE164        = big.NewInt(1 << 1)
	getSettingsSmsResponseSmsNumbersItemFieldID          = big.NewInt(1 << 2)
	getSettingsSmsResponseSmsNumbersItemFieldLabel       = big.NewInt(1 << 3)
	getSettingsSmsResponseSmsNumbersItemFieldStatus      = big.NewInt(1 << 4)
)

type GetSettingsSmsResponseSmsNumbersItem struct {
	// Per-number brand prefix override; null inherits the account-wide prefix.
	BrandPrefix *string `json:"brandPrefix,omitempty" url:"brandPrefix,omitempty"`
	E164        *string `json:"e164,omitempty" url:"e164,omitempty"`
	ID          *string `json:"id,omitempty" url:"id,omitempty"`
	// User-set tag ("Marketing", "Support") shown in number pickers.
	Label  *string `json:"label,omitempty" url:"label,omitempty"`
	Status *string `json:"status,omitempty" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetSettingsSmsResponseSmsNumbersItem) GetBrandPrefix() *string {
	if g == nil {
		return nil
	}
	return g.BrandPrefix
}

func (g *GetSettingsSmsResponseSmsNumbersItem) GetE164() *string {
	if g == nil {
		return nil
	}
	return g.E164
}

func (g *GetSettingsSmsResponseSmsNumbersItem) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetSettingsSmsResponseSmsNumbersItem) GetLabel() *string {
	if g == nil {
		return nil
	}
	return g.Label
}

func (g *GetSettingsSmsResponseSmsNumbersItem) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetSettingsSmsResponseSmsNumbersItem) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetSettingsSmsResponseSmsNumbersItem) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetBrandPrefix sets the BrandPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSmsNumbersItem) SetBrandPrefix(brandPrefix *string) {
	g.BrandPrefix = brandPrefix
	g.require(getSettingsSmsResponseSmsNumbersItemFieldBrandPrefix)
}

// SetE164 sets the E164 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSmsNumbersItem) SetE164(e164 *string) {
	g.E164 = e164
	g.require(getSettingsSmsResponseSmsNumbersItemFieldE164)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSmsNumbersItem) SetID(id *string) {
	g.ID = id
	g.require(getSettingsSmsResponseSmsNumbersItemFieldID)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSmsNumbersItem) SetLabel(label *string) {
	g.Label = label
	g.require(getSettingsSmsResponseSmsNumbersItemFieldLabel)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSettingsSmsResponseSmsNumbersItem) SetStatus(status *string) {
	g.Status = status
	g.require(getSettingsSmsResponseSmsNumbersItemFieldStatus)
}

func (g *GetSettingsSmsResponseSmsNumbersItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSettingsSmsResponseSmsNumbersItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetSettingsSmsResponseSmsNumbersItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetSettingsSmsResponseSmsNumbersItem) MarshalJSON() ([]byte, error) {
	type embed GetSettingsSmsResponseSmsNumbersItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetSettingsSmsResponseSmsNumbersItem) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsageSmsResponseFieldSuccess = big.NewInt(1 << 0)
	getUsageSmsResponseFieldUsage   = big.NewInt(1 << 1)
)

type GetUsageSmsResponse struct {
	Success bool                            `json:"success" url:"success"`
	Usage   []*GetUsageSmsResponseUsageItem `json:"usage" url:"usage"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsageSmsResponse) GetSuccess() bool {
	if g == nil {
		return false
	}
	return g.Success
}

func (g *GetUsageSmsResponse) GetUsage() []*GetUsageSmsResponseUsageItem {
	if g == nil {
		return nil
	}
	return g.Usage
}

func (g *GetUsageSmsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetUsageSmsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsageSmsResponse) SetSuccess(success bool) {
	g.Success = success
	g.require(getUsageSmsResponseFieldSuccess)
}

// SetUsage sets the Usage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsageSmsResponse) SetUsage(usage []*GetUsageSmsResponseUsageItem) {
	g.Usage = usage
	g.require(getUsageSmsResponseFieldUsage)
}

func (g *GetUsageSmsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsageSmsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsageSmsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsageSmsResponse) MarshalJSON() ([]byte, error) {
	type embed GetUsageSmsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsageSmsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsageSmsResponseUsageItemFieldCreditsCharged = big.NewInt(1 << 0)
	getUsageSmsResponseUsageItemFieldDelivered      = big.NewInt(1 << 1)
	getUsageSmsResponseUsageItemFieldFailed         = big.NewInt(1 << 2)
	getUsageSmsResponseUsageItemFieldFromNumber     = big.NewInt(1 << 3)
	getUsageSmsResponseUsageItemFieldLastSentAt     = big.NewInt(1 << 4)
	getUsageSmsResponseUsageItemFieldTestSends      = big.NewInt(1 << 5)
	getUsageSmsResponseUsageItemFieldTotalSends     = big.NewInt(1 << 6)
)

type GetUsageSmsResponseUsageItem struct {
	CreditsCharged float64 `json:"creditsCharged" url:"creditsCharged"`
	Delivered      int     `json:"delivered" url:"delivered"`
	Failed         int     `json:"failed" url:"failed"`
	// Sending phone number.
	FromNumber string     `json:"fromNumber" url:"fromNumber"`
	LastSentAt *time.Time `json:"lastSentAt,omitempty" url:"lastSentAt,omitempty"`
	TestSends  int        `json:"testSends" url:"testSends"`
	TotalSends int        `json:"totalSends" url:"totalSends"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsageSmsResponseUsageItem) GetCreditsCharged() float64 {
	if g == nil {
		return 0
	}
	return g.CreditsCharged
}

func (g *GetUsageSmsResponseUsageItem) GetDelivered() int {
	if g == nil {
		return 0
	}
	return g.Delivered
}

func (g *GetUsageSmsResponseUsageItem) GetFailed() int {
	if g == nil {
		return 0
	}
	return g.Failed
}

func (g *GetUsageSmsResponseUsageItem) GetFromNumber() string {
	if g == nil {
		return ""
	}
	return g.FromNumber
}

func (g *GetUsageSmsResponseUsageItem) GetLastSentAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.LastSentAt
}

func (g *GetUsageSmsResponseUsageItem) GetTestSends() int {
	if g == nil {
		return 0
	}
	return g.TestSends
}

func (g *GetUsageSmsResponseUsageItem) GetTotalSends() int {
	if g == nil {
		return 0
	}
	return g.TotalSends
}

func (g *GetUsageSmsResponseUsageItem) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetUsageSmsResponseUsageItem) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCreditsCharged sets the CreditsCharged field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsageSmsResponseUsageItem) SetCreditsCharged(creditsCharged float64) {
	g.CreditsCharged = creditsCharged
	g.require(getUsageSmsResponseUsageItemFieldCreditsCharged)
}

// SetDelivered sets the Delivered field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsageSmsResponseUsageItem) SetDelivered(delivered int) {
	g.Delivered = delivered
	g.require(getUsageSmsResponseUsageItemFieldDelivered)
}

// SetFailed sets the Failed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsageSmsResponseUsageItem) SetFailed(failed int) {
	g.Failed = failed
	g.require(getUsageSmsResponseUsageItemFieldFailed)
}

// SetFromNumber sets the FromNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsageSmsResponseUsageItem) SetFromNumber(fromNumber string) {
	g.FromNumber = fromNumber
	g.require(getUsageSmsResponseUsageItemFieldFromNumber)
}

// SetLastSentAt sets the LastSentAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsageSmsResponseUsageItem) SetLastSentAt(lastSentAt *time.Time) {
	g.LastSentAt = lastSentAt
	g.require(getUsageSmsResponseUsageItemFieldLastSentAt)
}

// SetTestSends sets the TestSends field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsageSmsResponseUsageItem) SetTestSends(testSends int) {
	g.TestSends = testSends
	g.require(getUsageSmsResponseUsageItemFieldTestSends)
}

// SetTotalSends sets the TotalSends field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsageSmsResponseUsageItem) SetTotalSends(totalSends int) {
	g.TotalSends = totalSends
	g.require(getUsageSmsResponseUsageItemFieldTotalSends)
}

func (g *GetUsageSmsResponseUsageItem) UnmarshalJSON(data []byte) error {
	type embed GetUsageSmsResponseUsageItem
	var unmarshaler = struct {
		embed
		LastSentAt *internal.DateTime `json:"lastSentAt,omitempty"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetUsageSmsResponseUsageItem(unmarshaler.embed)
	g.LastSentAt = unmarshaler.LastSentAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsageSmsResponseUsageItem) MarshalJSON() ([]byte, error) {
	type embed GetUsageSmsResponseUsageItem
	var marshaler = struct {
		embed
		LastSentAt *internal.DateTime `json:"lastSentAt,omitempty"`
	}{
		embed:      embed(*g),
		LastSentAt: internal.NewOptionalDateTime(g.LastSentAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsageSmsResponseUsageItem) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	releaseNumberSmsResponseFieldMessage = big.NewInt(1 << 0)
	releaseNumberSmsResponseFieldNumber  = big.NewInt(1 << 1)
	releaseNumberSmsResponseFieldSuccess = big.NewInt(1 << 2)
)

type ReleaseNumberSmsResponse struct {
	Message string                          `json:"message" url:"message"`
	Number  *ReleaseNumberSmsResponseNumber `json:"number" url:"number"`
	Success bool                            `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReleaseNumberSmsResponse) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *ReleaseNumberSmsResponse) GetNumber() *ReleaseNumberSmsResponseNumber {
	if r == nil {
		return nil
	}
	return r.Number
}

func (r *ReleaseNumberSmsResponse) GetSuccess() bool {
	if r == nil {
		return false
	}
	return r.Success
}

func (r *ReleaseNumberSmsResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReleaseNumberSmsResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleaseNumberSmsResponse) SetMessage(message string) {
	r.Message = message
	r.require(releaseNumberSmsResponseFieldMessage)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleaseNumberSmsResponse) SetNumber(number *ReleaseNumberSmsResponseNumber) {
	r.Number = number
	r.require(releaseNumberSmsResponseFieldNumber)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleaseNumberSmsResponse) SetSuccess(success bool) {
	r.Success = success
	r.require(releaseNumberSmsResponseFieldSuccess)
}

func (r *ReleaseNumberSmsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ReleaseNumberSmsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReleaseNumberSmsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReleaseNumberSmsResponse) MarshalJSON() ([]byte, error) {
	type embed ReleaseNumberSmsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReleaseNumberSmsResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	releaseNumberSmsResponseNumberFieldID     = big.NewInt(1 << 0)
	releaseNumberSmsResponseNumberFieldStatus = big.NewInt(1 << 1)
)

type ReleaseNumberSmsResponseNumber struct {
	ID     string                               `json:"id" url:"id"`
	Status ReleaseNumberSmsResponseNumberStatus `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReleaseNumberSmsResponseNumber) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReleaseNumberSmsResponseNumber) GetStatus() ReleaseNumberSmsResponseNumberStatus {
	if r == nil {
		return ""
	}
	return r.Status
}

func (r *ReleaseNumberSmsResponseNumber) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReleaseNumberSmsResponseNumber) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleaseNumberSmsResponseNumber) SetID(id string) {
	r.ID = id
	r.require(releaseNumberSmsResponseNumberFieldID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleaseNumberSmsResponseNumber) SetStatus(status ReleaseNumberSmsResponseNumberStatus) {
	r.Status = status
	r.require(releaseNumberSmsResponseNumberFieldStatus)
}

func (r *ReleaseNumberSmsResponseNumber) UnmarshalJSON(data []byte) error {
	type unmarshaler ReleaseNumberSmsResponseNumber
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReleaseNumberSmsResponseNumber(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReleaseNumberSmsResponseNumber) MarshalJSON() ([]byte, error) {
	type embed ReleaseNumberSmsResponseNumber
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReleaseNumberSmsResponseNumber) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReleaseNumberSmsResponseNumberStatus string

const (
	ReleaseNumberSmsResponseNumberStatusReleased ReleaseNumberSmsResponseNumberStatus = "released"
)

func NewReleaseNumberSmsResponseNumberStatusFromString(s string) (ReleaseNumberSmsResponseNumberStatus, error) {
	switch s {
	case "released":
		return ReleaseNumberSmsResponseNumberStatusReleased, nil
	}
	var t ReleaseNumberSmsResponseNumberStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReleaseNumberSmsResponseNumberStatus) Ptr() *ReleaseNumberSmsResponseNumberStatus {
	return &r
}

var (
	sendTestSmsResponseFieldMessage   = big.NewInt(1 << 0)
	sendTestSmsResponseFieldSmsSendID = big.NewInt(1 << 1)
	sendTestSmsResponseFieldSuccess   = big.NewInt(1 << 2)
	sendTestSmsResponseFieldToPhone   = big.NewInt(1 << 3)
)

type SendTestSmsResponse struct {
	Message   *string `json:"message,omitempty" url:"message,omitempty"`
	SmsSendID *string `json:"smsSendId,omitempty" url:"smsSendId,omitempty"`
	Success   *bool   `json:"success,omitempty" url:"success,omitempty"`
	ToPhone   *string `json:"toPhone,omitempty" url:"toPhone,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SendTestSmsResponse) GetMessage() *string {
	if s == nil {
		return nil
	}
	return s.Message
}

func (s *SendTestSmsResponse) GetSmsSendID() *string {
	if s == nil {
		return nil
	}
	return s.SmsSendID
}

func (s *SendTestSmsResponse) GetSuccess() *bool {
	if s == nil {
		return nil
	}
	return s.Success
}

func (s *SendTestSmsResponse) GetToPhone() *string {
	if s == nil {
		return nil
	}
	return s.ToPhone
}

func (s *SendTestSmsResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SendTestSmsResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendTestSmsResponse) SetMessage(message *string) {
	s.Message = message
	s.require(sendTestSmsResponseFieldMessage)
}

// SetSmsSendID sets the SmsSendID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendTestSmsResponse) SetSmsSendID(smsSendID *string) {
	s.SmsSendID = smsSendID
	s.require(sendTestSmsResponseFieldSmsSendID)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendTestSmsResponse) SetSuccess(success *bool) {
	s.Success = success
	s.require(sendTestSmsResponseFieldSuccess)
}

// SetToPhone sets the ToPhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendTestSmsResponse) SetToPhone(toPhone *string) {
	s.ToPhone = toPhone
	s.require(sendTestSmsResponseFieldToPhone)
}

func (s *SendTestSmsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SendTestSmsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SendTestSmsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SendTestSmsResponse) MarshalJSON() ([]byte, error) {
	type embed SendTestSmsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SendTestSmsResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	updateNumberLabelSmsResponseFieldMessage = big.NewInt(1 << 0)
	updateNumberLabelSmsResponseFieldNumber  = big.NewInt(1 << 1)
	updateNumberLabelSmsResponseFieldSuccess = big.NewInt(1 << 2)
)

type UpdateNumberLabelSmsResponse struct {
	Message *string                             `json:"message,omitempty" url:"message,omitempty"`
	Number  *UpdateNumberLabelSmsResponseNumber `json:"number,omitempty" url:"number,omitempty"`
	Success *bool                               `json:"success,omitempty" url:"success,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateNumberLabelSmsResponse) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

func (u *UpdateNumberLabelSmsResponse) GetNumber() *UpdateNumberLabelSmsResponseNumber {
	if u == nil {
		return nil
	}
	return u.Number
}

func (u *UpdateNumberLabelSmsResponse) GetSuccess() *bool {
	if u == nil {
		return nil
	}
	return u.Success
}

func (u *UpdateNumberLabelSmsResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateNumberLabelSmsResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberLabelSmsResponse) SetMessage(message *string) {
	u.Message = message
	u.require(updateNumberLabelSmsResponseFieldMessage)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberLabelSmsResponse) SetNumber(number *UpdateNumberLabelSmsResponseNumber) {
	u.Number = number
	u.require(updateNumberLabelSmsResponseFieldNumber)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberLabelSmsResponse) SetSuccess(success *bool) {
	u.Success = success
	u.require(updateNumberLabelSmsResponseFieldSuccess)
}

func (u *UpdateNumberLabelSmsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateNumberLabelSmsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateNumberLabelSmsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateNumberLabelSmsResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateNumberLabelSmsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateNumberLabelSmsResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateNumberLabelSmsResponseNumberFieldBrandPrefix = big.NewInt(1 << 0)
	updateNumberLabelSmsResponseNumberFieldID          = big.NewInt(1 << 1)
	updateNumberLabelSmsResponseNumberFieldLabel       = big.NewInt(1 << 2)
)

type UpdateNumberLabelSmsResponseNumber struct {
	BrandPrefix *string `json:"brandPrefix,omitempty" url:"brandPrefix,omitempty"`
	ID          *string `json:"id,omitempty" url:"id,omitempty"`
	Label       *string `json:"label,omitempty" url:"label,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateNumberLabelSmsResponseNumber) GetBrandPrefix() *string {
	if u == nil {
		return nil
	}
	return u.BrandPrefix
}

func (u *UpdateNumberLabelSmsResponseNumber) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UpdateNumberLabelSmsResponseNumber) GetLabel() *string {
	if u == nil {
		return nil
	}
	return u.Label
}

func (u *UpdateNumberLabelSmsResponseNumber) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateNumberLabelSmsResponseNumber) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetBrandPrefix sets the BrandPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberLabelSmsResponseNumber) SetBrandPrefix(brandPrefix *string) {
	u.BrandPrefix = brandPrefix
	u.require(updateNumberLabelSmsResponseNumberFieldBrandPrefix)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberLabelSmsResponseNumber) SetID(id *string) {
	u.ID = id
	u.require(updateNumberLabelSmsResponseNumberFieldID)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberLabelSmsResponseNumber) SetLabel(label *string) {
	u.Label = label
	u.require(updateNumberLabelSmsResponseNumberFieldLabel)
}

func (u *UpdateNumberLabelSmsResponseNumber) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateNumberLabelSmsResponseNumber
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateNumberLabelSmsResponseNumber(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateNumberLabelSmsResponseNumber) MarshalJSON() ([]byte, error) {
	type embed UpdateNumberLabelSmsResponseNumber
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateNumberLabelSmsResponseNumber) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateNumberLabelSmsRequestFieldNumberID    = big.NewInt(1 << 0)
	updateNumberLabelSmsRequestFieldBrandPrefix = big.NewInt(1 << 1)
	updateNumberLabelSmsRequestFieldLabel       = big.NewInt(1 << 2)
)

type UpdateNumberLabelSmsRequest struct {
	// SMS number ID returned by Get SMS Settings.
	NumberID string `json:"-" url:"-"`
	// Per-number brand prefix override; messages send as "{prefix}: your message". Send null to clear it back to the account-wide prefix.
	BrandPrefix *string `json:"brandPrefix,omitempty" url:"-"`
	// Label such as Marketing or Support. Send null to clear it.
	Label *string `json:"label,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateNumberLabelSmsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetNumberID sets the NumberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberLabelSmsRequest) SetNumberID(numberID string) {
	u.NumberID = numberID
	u.require(updateNumberLabelSmsRequestFieldNumberID)
}

// SetBrandPrefix sets the BrandPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberLabelSmsRequest) SetBrandPrefix(brandPrefix *string) {
	u.BrandPrefix = brandPrefix
	u.require(updateNumberLabelSmsRequestFieldBrandPrefix)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberLabelSmsRequest) SetLabel(label *string) {
	u.Label = label
	u.require(updateNumberLabelSmsRequestFieldLabel)
}

func (u *UpdateNumberLabelSmsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateNumberLabelSmsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateNumberLabelSmsRequest(body)
	return nil
}

func (u *UpdateNumberLabelSmsRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateNumberLabelSmsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
