// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersSetTrackingDomainRequest(t *testing.T) {
	t.Run("SetDomain", func(t *testing.T) {
		obj := &SetTrackingDomainRequest{}
		var fernTestValueDomain string
		obj.SetDomain(fernTestValueDomain)
		assert.Equal(t, fernTestValueDomain, obj.Domain)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSetTrackingDomainRequest(t *testing.T) {
	t.Run("SetDomain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainRequest{}
		var fernTestValueDomain string

		// Act
		obj.SetDomain(fernTestValueDomain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTrackingDomain(t *testing.T) {
	t.Run("SetActive", func(t *testing.T) {
		obj := &TrackingDomain{}
		var fernTestValueActive bool
		obj.SetActive(fernTestValueActive)
		assert.Equal(t, fernTestValueActive, obj.Active)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCnameRecord", func(t *testing.T) {
		obj := &TrackingDomain{}
		var fernTestValueCnameRecord *TrackingDomainCnameRecord
		obj.SetCnameRecord(fernTestValueCnameRecord)
		assert.Equal(t, fernTestValueCnameRecord, obj.CnameRecord)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomain", func(t *testing.T) {
		obj := &TrackingDomain{}
		var fernTestValueDomain string
		obj.SetDomain(fernTestValueDomain)
		assert.Equal(t, fernTestValueDomain, obj.Domain)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetError", func(t *testing.T) {
		obj := &TrackingDomain{}
		var fernTestValueError *string
		obj.SetError(fernTestValueError)
		assert.Equal(t, fernTestValueError, obj.Error)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEverVerified", func(t *testing.T) {
		obj := &TrackingDomain{}
		var fernTestValueEverVerified bool
		obj.SetEverVerified(fernTestValueEverVerified)
		assert.Equal(t, fernTestValueEverVerified, obj.EverVerified)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLastCheckedAt", func(t *testing.T) {
		obj := &TrackingDomain{}
		var fernTestValueLastCheckedAt *time.Time
		obj.SetLastCheckedAt(fernTestValueLastCheckedAt)
		assert.Equal(t, fernTestValueLastCheckedAt, obj.LastCheckedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSslStatus", func(t *testing.T) {
		obj := &TrackingDomain{}
		var fernTestValueSslStatus *string
		obj.SetSslStatus(fernTestValueSslStatus)
		assert.Equal(t, fernTestValueSslStatus, obj.SslStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &TrackingDomain{}
		var fernTestValueStatus TrackingDomainStatus
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVerifiedAt", func(t *testing.T) {
		obj := &TrackingDomain{}
		var fernTestValueVerifiedAt *time.Time
		obj.SetVerifiedAt(fernTestValueVerifiedAt)
		assert.Equal(t, fernTestValueVerifiedAt, obj.VerifiedAt)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTrackingDomain(t *testing.T) {
	t.Run("GetActive", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var expected bool
		obj.Active = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetActive(), "getter should return the property value")
	})

	t.Run("GetActive_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetActive() // Should return zero value
	})

	t.Run("GetCnameRecord", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var expected *TrackingDomainCnameRecord
		obj.CnameRecord = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCnameRecord(), "getter should return the property value")
	})

	t.Run("GetCnameRecord_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		obj.CnameRecord = nil

		// Act & Assert
		assert.Nil(t, obj.GetCnameRecord(), "getter should return nil when property is nil")
	})

	t.Run("GetCnameRecord_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCnameRecord() // Should return zero value
	})

	t.Run("GetDomain", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var expected string
		obj.Domain = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomain(), "getter should return the property value")
	})

	t.Run("GetDomain_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomain() // Should return zero value
	})

	t.Run("GetError", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var expected *string
		obj.Error = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetError(), "getter should return the property value")
	})

	t.Run("GetError_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		obj.Error = nil

		// Act & Assert
		assert.Nil(t, obj.GetError(), "getter should return nil when property is nil")
	})

	t.Run("GetError_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetError() // Should return zero value
	})

	t.Run("GetEverVerified", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var expected bool
		obj.EverVerified = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEverVerified(), "getter should return the property value")
	})

	t.Run("GetEverVerified_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEverVerified() // Should return zero value
	})

	t.Run("GetLastCheckedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var expected *time.Time
		obj.LastCheckedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLastCheckedAt(), "getter should return the property value")
	})

	t.Run("GetLastCheckedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		obj.LastCheckedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetLastCheckedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetLastCheckedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLastCheckedAt() // Should return zero value
	})

	t.Run("GetSslStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var expected *string
		obj.SslStatus = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSslStatus(), "getter should return the property value")
	})

	t.Run("GetSslStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		obj.SslStatus = nil

		// Act & Assert
		assert.Nil(t, obj.GetSslStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetSslStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSslStatus() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var expected TrackingDomainStatus
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetVerifiedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var expected *time.Time
		obj.VerifiedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVerifiedAt(), "getter should return the property value")
	})

	t.Run("GetVerifiedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		obj.VerifiedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetVerifiedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetVerifiedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVerifiedAt() // Should return zero value
	})

}

func TestSettersMarkExplicitTrackingDomain(t *testing.T) {
	t.Run("SetActive_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var fernTestValueActive bool

		// Act
		obj.SetActive(fernTestValueActive)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCnameRecord_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var fernTestValueCnameRecord *TrackingDomainCnameRecord

		// Act
		obj.SetCnameRecord(fernTestValueCnameRecord)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var fernTestValueDomain string

		// Act
		obj.SetDomain(fernTestValueDomain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetError_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var fernTestValueError *string

		// Act
		obj.SetError(fernTestValueError)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEverVerified_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var fernTestValueEverVerified bool

		// Act
		obj.SetEverVerified(fernTestValueEverVerified)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLastCheckedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var fernTestValueLastCheckedAt *time.Time

		// Act
		obj.SetLastCheckedAt(fernTestValueLastCheckedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSslStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var fernTestValueSslStatus *string

		// Act
		obj.SetSslStatus(fernTestValueSslStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var fernTestValueStatus TrackingDomainStatus

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVerifiedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}
		var fernTestValueVerifiedAt *time.Time

		// Act
		obj.SetVerifiedAt(fernTestValueVerifiedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTrackingDomainCnameRecord(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &TrackingDomainCnameRecord{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetType", func(t *testing.T) {
		obj := &TrackingDomainCnameRecord{}
		var fernTestValueType *TrackingDomainCnameRecordType
		obj.SetType(fernTestValueType)
		assert.Equal(t, fernTestValueType, obj.Type)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetValue", func(t *testing.T) {
		obj := &TrackingDomainCnameRecord{}
		var fernTestValueValue *string
		obj.SetValue(fernTestValueValue)
		assert.Equal(t, fernTestValueValue, obj.Value)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTrackingDomainCnameRecord(t *testing.T) {
	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomainCnameRecord{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomainCnameRecord{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomainCnameRecord
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomainCnameRecord{}
		var expected *TrackingDomainCnameRecordType
		obj.Type = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetType(), "getter should return the property value")
	})

	t.Run("GetType_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomainCnameRecord{}
		obj.Type = nil

		// Act & Assert
		assert.Nil(t, obj.GetType(), "getter should return nil when property is nil")
	})

	t.Run("GetType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomainCnameRecord
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetType() // Should return zero value
	})

	t.Run("GetValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomainCnameRecord{}
		var expected *string
		obj.Value = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetValue(), "getter should return the property value")
	})

	t.Run("GetValue_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomainCnameRecord{}
		obj.Value = nil

		// Act & Assert
		assert.Nil(t, obj.GetValue(), "getter should return nil when property is nil")
	})

	t.Run("GetValue_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomainCnameRecord
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetValue() // Should return zero value
	})

}

func TestSettersMarkExplicitTrackingDomainCnameRecord(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomainCnameRecord{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomainCnameRecord{}
		var fernTestValueType *TrackingDomainCnameRecordType

		// Act
		obj.SetType(fernTestValueType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetValue_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomainCnameRecord{}
		var fernTestValueValue *string

		// Act
		obj.SetValue(fernTestValueValue)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetTrackingDomainResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &GetTrackingDomainResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTrackingDomain", func(t *testing.T) {
		obj := &GetTrackingDomainResponse{}
		var fernTestValueTrackingDomain *TrackingDomain
		obj.SetTrackingDomain(fernTestValueTrackingDomain)
		assert.Equal(t, fernTestValueTrackingDomain, obj.TrackingDomain)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetTrackingDomainResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetTrackingDomainResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetTrackingDomainResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetTrackingDomain", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetTrackingDomainResponse{}
		var expected *TrackingDomain
		obj.TrackingDomain = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTrackingDomain(), "getter should return the property value")
	})

	t.Run("GetTrackingDomain_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetTrackingDomainResponse{}
		obj.TrackingDomain = nil

		// Act & Assert
		assert.Nil(t, obj.GetTrackingDomain(), "getter should return nil when property is nil")
	})

	t.Run("GetTrackingDomain_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTrackingDomain() // Should return zero value
	})

}

func TestSettersMarkExplicitGetTrackingDomainResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetTrackingDomainResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTrackingDomain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetTrackingDomainResponse{}
		var fernTestValueTrackingDomain *TrackingDomain

		// Act
		obj.SetTrackingDomain(fernTestValueTrackingDomain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRemoveTrackingDomainResponse(t *testing.T) {
	t.Run("SetRemoved", func(t *testing.T) {
		obj := &RemoveTrackingDomainResponse{}
		var fernTestValueRemoved *bool
		obj.SetRemoved(fernTestValueRemoved)
		assert.Equal(t, fernTestValueRemoved, obj.Removed)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccess", func(t *testing.T) {
		obj := &RemoveTrackingDomainResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTrackingDomain", func(t *testing.T) {
		obj := &RemoveTrackingDomainResponse{}
		var fernTestValueTrackingDomain any
		obj.SetTrackingDomain(fernTestValueTrackingDomain)
		assert.Equal(t, fernTestValueTrackingDomain, obj.TrackingDomain)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersRemoveTrackingDomainResponse(t *testing.T) {
	t.Run("GetRemoved", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveTrackingDomainResponse{}
		var expected *bool
		obj.Removed = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRemoved(), "getter should return the property value")
	})

	t.Run("GetRemoved_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveTrackingDomainResponse{}
		obj.Removed = nil

		// Act & Assert
		assert.Nil(t, obj.GetRemoved(), "getter should return nil when property is nil")
	})

	t.Run("GetRemoved_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RemoveTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRemoved() // Should return zero value
	})

	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveTrackingDomainResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveTrackingDomainResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RemoveTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetTrackingDomain", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveTrackingDomainResponse{}
		var expected any
		obj.TrackingDomain = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTrackingDomain(), "getter should return the property value")
	})

	t.Run("GetTrackingDomain_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RemoveTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTrackingDomain() // Should return zero value
	})

}

func TestSettersMarkExplicitRemoveTrackingDomainResponse(t *testing.T) {
	t.Run("SetRemoved_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveTrackingDomainResponse{}
		var fernTestValueRemoved *bool

		// Act
		obj.SetRemoved(fernTestValueRemoved)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveTrackingDomainResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTrackingDomain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveTrackingDomainResponse{}
		var fernTestValueTrackingDomain any

		// Act
		obj.SetTrackingDomain(fernTestValueTrackingDomain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSetTrackingDomainResponse(t *testing.T) {
	t.Run("SetMessage", func(t *testing.T) {
		obj := &SetTrackingDomainResponse{}
		var fernTestValueMessage *string
		obj.SetMessage(fernTestValueMessage)
		assert.Equal(t, fernTestValueMessage, obj.Message)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccess", func(t *testing.T) {
		obj := &SetTrackingDomainResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTrackingDomain", func(t *testing.T) {
		obj := &SetTrackingDomainResponse{}
		var fernTestValueTrackingDomain *TrackingDomain
		obj.SetTrackingDomain(fernTestValueTrackingDomain)
		assert.Equal(t, fernTestValueTrackingDomain, obj.TrackingDomain)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSetTrackingDomainResponse(t *testing.T) {
	t.Run("GetMessage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainResponse{}
		var expected *string
		obj.Message = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMessage(), "getter should return the property value")
	})

	t.Run("GetMessage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainResponse{}
		obj.Message = nil

		// Act & Assert
		assert.Nil(t, obj.GetMessage(), "getter should return nil when property is nil")
	})

	t.Run("GetMessage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SetTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMessage() // Should return zero value
	})

	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SetTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetTrackingDomain", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainResponse{}
		var expected *TrackingDomain
		obj.TrackingDomain = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTrackingDomain(), "getter should return the property value")
	})

	t.Run("GetTrackingDomain_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainResponse{}
		obj.TrackingDomain = nil

		// Act & Assert
		assert.Nil(t, obj.GetTrackingDomain(), "getter should return nil when property is nil")
	})

	t.Run("GetTrackingDomain_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SetTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTrackingDomain() // Should return zero value
	})

}

func TestSettersMarkExplicitSetTrackingDomainResponse(t *testing.T) {
	t.Run("SetMessage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainResponse{}
		var fernTestValueMessage *string

		// Act
		obj.SetMessage(fernTestValueMessage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTrackingDomain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainResponse{}
		var fernTestValueTrackingDomain *TrackingDomain

		// Act
		obj.SetTrackingDomain(fernTestValueTrackingDomain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersVerifyTrackingDomainResponse(t *testing.T) {
	t.Run("SetMessage", func(t *testing.T) {
		obj := &VerifyTrackingDomainResponse{}
		var fernTestValueMessage *string
		obj.SetMessage(fernTestValueMessage)
		assert.Equal(t, fernTestValueMessage, obj.Message)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccess", func(t *testing.T) {
		obj := &VerifyTrackingDomainResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTrackingDomain", func(t *testing.T) {
		obj := &VerifyTrackingDomainResponse{}
		var fernTestValueTrackingDomain *TrackingDomain
		obj.SetTrackingDomain(fernTestValueTrackingDomain)
		assert.Equal(t, fernTestValueTrackingDomain, obj.TrackingDomain)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVerified", func(t *testing.T) {
		obj := &VerifyTrackingDomainResponse{}
		var fernTestValueVerified *bool
		obj.SetVerified(fernTestValueVerified)
		assert.Equal(t, fernTestValueVerified, obj.Verified)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersVerifyTrackingDomainResponse(t *testing.T) {
	t.Run("GetMessage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		var expected *string
		obj.Message = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMessage(), "getter should return the property value")
	})

	t.Run("GetMessage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		obj.Message = nil

		// Act & Assert
		assert.Nil(t, obj.GetMessage(), "getter should return nil when property is nil")
	})

	t.Run("GetMessage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VerifyTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMessage() // Should return zero value
	})

	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VerifyTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetTrackingDomain", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		var expected *TrackingDomain
		obj.TrackingDomain = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTrackingDomain(), "getter should return the property value")
	})

	t.Run("GetTrackingDomain_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		obj.TrackingDomain = nil

		// Act & Assert
		assert.Nil(t, obj.GetTrackingDomain(), "getter should return nil when property is nil")
	})

	t.Run("GetTrackingDomain_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VerifyTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTrackingDomain() // Should return zero value
	})

	t.Run("GetVerified", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		var expected *bool
		obj.Verified = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVerified(), "getter should return the property value")
	})

	t.Run("GetVerified_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		obj.Verified = nil

		// Act & Assert
		assert.Nil(t, obj.GetVerified(), "getter should return nil when property is nil")
	})

	t.Run("GetVerified_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VerifyTrackingDomainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVerified() // Should return zero value
	})

}

func TestSettersMarkExplicitVerifyTrackingDomainResponse(t *testing.T) {
	t.Run("SetMessage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		var fernTestValueMessage *string

		// Act
		obj.SetMessage(fernTestValueMessage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTrackingDomain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		var fernTestValueTrackingDomain *TrackingDomain

		// Act
		obj.SetTrackingDomain(fernTestValueTrackingDomain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVerified_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}
		var fernTestValueVerified *bool

		// Act
		obj.SetVerified(fernTestValueVerified)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingGetTrackingDomainResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetTrackingDomainResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetTrackingDomainResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetTrackingDomainResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetTrackingDomainResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingRemoveTrackingDomainResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveTrackingDomainResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled RemoveTrackingDomainResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj RemoveTrackingDomainResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj RemoveTrackingDomainResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingSetTrackingDomainResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetTrackingDomainResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SetTrackingDomainResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SetTrackingDomainResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SetTrackingDomainResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingTrackingDomain(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomain{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TrackingDomain
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TrackingDomain
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TrackingDomain
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingTrackingDomainCnameRecord(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TrackingDomainCnameRecord{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TrackingDomainCnameRecord
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TrackingDomainCnameRecord
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TrackingDomainCnameRecord
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingVerifyTrackingDomainResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyTrackingDomainResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled VerifyTrackingDomainResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj VerifyTrackingDomainResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj VerifyTrackingDomainResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringGetTrackingDomainResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetTrackingDomainResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetTrackingDomainResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringRemoveTrackingDomainResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &RemoveTrackingDomainResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RemoveTrackingDomainResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringSetTrackingDomainResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SetTrackingDomainResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SetTrackingDomainResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringTrackingDomain(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TrackingDomain{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringTrackingDomainCnameRecord(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TrackingDomainCnameRecord{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomainCnameRecord
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringVerifyTrackingDomainResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &VerifyTrackingDomainResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VerifyTrackingDomainResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumTrackingDomainCnameRecordType(t *testing.T) {
	t.Run("NewFromString_CNAME", func(t *testing.T) {
		t.Parallel()
		val, err := NewTrackingDomainCnameRecordTypeFromString("CNAME")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TrackingDomainCnameRecordType("CNAME"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewTrackingDomainCnameRecordTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewTrackingDomainCnameRecordTypeFromString("CNAME")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumTrackingDomainStatus(t *testing.T) {
	t.Run("NewFromString_not_started", func(t *testing.T) {
		t.Parallel()
		val, err := NewTrackingDomainStatusFromString("not_started")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TrackingDomainStatus("not_started"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_pending", func(t *testing.T) {
		t.Parallel()
		val, err := NewTrackingDomainStatusFromString("pending")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TrackingDomainStatus("pending"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_verified", func(t *testing.T) {
		t.Parallel()
		val, err := NewTrackingDomainStatusFromString("verified")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TrackingDomainStatus("verified"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewTrackingDomainStatusFromString("failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TrackingDomainStatus("failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewTrackingDomainStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewTrackingDomainStatusFromString("not_started")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesGetTrackingDomainResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetTrackingDomainResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetTrackingDomainResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesRemoveTrackingDomainResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &RemoveTrackingDomainResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RemoveTrackingDomainResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesSetTrackingDomainResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SetTrackingDomainResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SetTrackingDomainResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesTrackingDomain(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TrackingDomain{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomain
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesTrackingDomainCnameRecord(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TrackingDomainCnameRecord{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TrackingDomainCnameRecord
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesVerifyTrackingDomainResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &VerifyTrackingDomainResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VerifyTrackingDomainResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
