// Code generated by Fern. DO NOT EDIT.

package dataexports

import (
	context "context"
	http "net/http"

	sequenzygo "github.com/sequenzy/sequenzy-go"
	core "github.com/sequenzy/sequenzy-go/core"
	internal "github.com/sequenzy/sequenzy-go/internal"
	option "github.com/sequenzy/sequenzy-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) CreateDataExport(
	ctx context.Context,
	request *sequenzygo.CreateDataExportRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.CreateDataExportResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := baseURL + "/data-exports"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *sequenzygo.CreateDataExportResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.CreateDataExportResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteDataExport(
	ctx context.Context,
	request *sequenzygo.DeleteDataExportRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.DeleteDataExportResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/data-exports/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *sequenzygo.DeleteDataExportResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.DeleteDataExportResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetDataExport(
	ctx context.Context,
	request *sequenzygo.GetDataExportRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.GetDataExportResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/data-exports/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *sequenzygo.GetDataExportResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.GetDataExportResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListDataExportRuns(
	ctx context.Context,
	request *sequenzygo.ListDataExportRunsRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.ListDataExportRunsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/data-exports/%v/runs",
		request.ID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *sequenzygo.ListDataExportRunsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.ListDataExportRunsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListDataExports(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.ListDataExportsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := baseURL + "/data-exports"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *sequenzygo.ListDataExportsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.ListDataExportsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RunDataExport(
	ctx context.Context,
	request *sequenzygo.RunDataExportRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.RunDataExportResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/data-exports/%v/run",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *sequenzygo.RunDataExportResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.RunDataExportResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) TestDataExport(
	ctx context.Context,
	request *sequenzygo.TestDataExportRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.TestDataExportResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/data-exports/%v/test",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *sequenzygo.TestDataExportResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.TestDataExportResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateDataExport(
	ctx context.Context,
	request *sequenzygo.UpdateDataExportRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.UpdateDataExportResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/data-exports/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *sequenzygo.UpdateDataExportResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.UpdateDataExportResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
