// Code generated by Fern. DO NOT EDIT.

package conversations

import (
	context "context"

	sequenzygo "github.com/sequenzy/sequenzy-go"
	core "github.com/sequenzy/sequenzy-go/core"
	internal "github.com/sequenzy/sequenzy-go/internal"
	option "github.com/sequenzy/sequenzy-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Opens or closes up to 100 conversations in one request. Only conversations whose status changes are updated, so retries are safe. IDs that do not exist in the company are reported in `notFoundIds` and do not fail the request.
//
// Example:
//
//	request := &sequenzygo.BulkUpdateStatusConversationsRequest{
//	    ConversationIDs: []string{
//	        "conversationIds",
//	    },
//	    Status: sequenzygo.BulkUpdateStatusConversationsRequestStatusOpen,
//	}
//	client.Conversations.BulkUpdateStatus(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) BulkUpdateStatus(
	ctx context.Context,
	request *sequenzygo.BulkUpdateStatusConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.BulkUpdateStatusConversationsResponse, error) {
	response, err := c.WithRawResponse.BulkUpdateStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Emails a copy of one received or sent message, with its stored attachments up to 15 MB in total (files left out are listed in the forwarded email), to another address. The forward is recorded in the conversation as a system message whose deliveryStatus moves from pending to sent or failed. It does not change the conversation's status, unread state, or last activity. Notes cannot be forwarded.
//
// Example:
//
//	request := &sequenzygo.ForwardMessageConversationsRequest{
//	    ConversationID: "conversationId",
//	    MessageID: "messageId",
//	    To: "to",
//	}
//	client.Conversations.ForwardMessage(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ForwardMessage(
	ctx context.Context,
	request *sequenzygo.ForwardMessageConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.ForwardMessageConversationsResponse, error) {
	response, err := c.WithRawResponse.ForwardMessage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns one conversation with all messages, originating campaign or sequence context, and subscriber details. Stored attachments include a signed downloadUrl valid for one hour.
//
// Example:
//
//	request := &sequenzygo.GetConversationsRequest{
//	    ConversationID: "conversationId",
//	}
//	client.Conversations.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *sequenzygo.GetConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.GetConversationsResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the address anyone can email to reach this company's inbox, the same address on verified custom inbound domains, whether receiving is on, whether attachments are stored, and how long received email is kept.
//
// Example:
//
//	client.Conversations.GetInboxAddress(
//	    context.TODO(),
//	)
func (c *Client) GetInboxAddress(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sequenzygo.GetInboxAddressResponse, error) {
	response, err := c.WithRawResponse.GetInboxAddress(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Lists inbox conversations: replies to your campaigns, sequences, and transactional email, plus email sent to your inbox address. Filter by status, unread flag, or search term.
//
// Example:
//
//	request := &sequenzygo.ListConversationsRequest{}
//	client.Conversations.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *sequenzygo.ListConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.ListConversationsResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Marks all unread inbound messages in a conversation as read and clears the unread flag.
//
// Example:
//
//	request := &sequenzygo.MarkReadConversationsRequest{
//	    ConversationID: "conversationId",
//	}
//	client.Conversations.MarkRead(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) MarkRead(
	ctx context.Context,
	request *sequenzygo.MarkReadConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.MarkReadConversationsResponse, error) {
	response, err := c.WithRawResponse.MarkRead(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Sets the conversation's unread flag and marks its latest received message unread.
//
// Example:
//
//	request := &sequenzygo.MarkUnreadConversationsRequest{
//	    ConversationID: "conversationId",
//	}
//	client.Conversations.MarkUnread(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) MarkUnread(
	ctx context.Context,
	request *sequenzygo.MarkUnreadConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.MarkUnreadConversationsResponse, error) {
	response, err := c.WithRawResponse.MarkUnread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Sends an email reply to the subscriber or adds an internal note. Replies reopen closed conversations.
//
// Example:
//
//	request := &sequenzygo.SendMessageConversationsRequest{
//	    ConversationID: "conversationId",
//	}
//	client.Conversations.SendMessage(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) SendMessage(
	ctx context.Context,
	request *sequenzygo.SendMessageConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.SendMessageConversationsResponse, error) {
	response, err := c.WithRawResponse.SendMessage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Sets a branded inbox address `{localPart}@inbound.{domain}` on one of your verified sending domains, or clears it when both fields are null. The address starts receiving once the domain's inbound MX record is verified; the default address keeps working. Returns the same body as Get Inbox Address.
//
// Example:
//
//	request := &sequenzygo.UpdateInboxAddressRequest{}
//	client.Conversations.UpdateInboxAddress(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateInboxAddress(
	ctx context.Context,
	request *sequenzygo.UpdateInboxAddressRequest,
	opts ...option.RequestOption,
) (*sequenzygo.UpdateInboxAddressResponse, error) {
	response, err := c.WithRawResponse.UpdateInboxAddress(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Opens or closes a conversation.
//
// Example:
//
//	request := &sequenzygo.UpdateStatusConversationsRequest{
//	    ConversationID: "conversationId",
//	    Status: sequenzygo.UpdateStatusConversationsRequestStatusOpen,
//	}
//	client.Conversations.UpdateStatus(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateStatus(
	ctx context.Context,
	request *sequenzygo.UpdateStatusConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.UpdateStatusConversationsResponse, error) {
	response, err := c.WithRawResponse.UpdateStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
