// Code generated by Fern. DO NOT EDIT.

package conversations

import (
	context "context"

	sequenzygo "github.com/sequenzy/sequenzy-go"
	core "github.com/sequenzy/sequenzy-go/core"
	internal "github.com/sequenzy/sequenzy-go/internal"
	option "github.com/sequenzy/sequenzy-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns one conversation with all messages, originating campaign or sequence context, and subscriber details.
//
// Example:
//
//	request := &sequenzygo.GetConversationsRequest{
//	    ConversationID: "conversationId",
//	}
//	client.Conversations.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *sequenzygo.GetConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.GetConversationsResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Lists inbox conversations with subscriber replies, filtered by status, unread flag, or search term.
//
// Example:
//
//	request := &sequenzygo.ListConversationsRequest{}
//	client.Conversations.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *sequenzygo.ListConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.ListConversationsResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Marks all unread inbound messages in a conversation as read and clears the unread flag.
//
// Example:
//
//	request := &sequenzygo.MarkReadConversationsRequest{
//	    ConversationID: "conversationId",
//	}
//	client.Conversations.MarkRead(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) MarkRead(
	ctx context.Context,
	request *sequenzygo.MarkReadConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.MarkReadConversationsResponse, error) {
	response, err := c.WithRawResponse.MarkRead(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Sends an email reply to the subscriber or adds an internal note. Replies reopen closed conversations.
//
// Example:
//
//	request := &sequenzygo.SendMessageConversationsRequest{
//	    ConversationID: "conversationId",
//	}
//	client.Conversations.SendMessage(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) SendMessage(
	ctx context.Context,
	request *sequenzygo.SendMessageConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.SendMessageConversationsResponse, error) {
	response, err := c.WithRawResponse.SendMessage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Opens or closes a conversation.
//
// Example:
//
//	request := &sequenzygo.UpdateStatusConversationsRequest{
//	    ConversationID: "conversationId",
//	    Status: sequenzygo.UpdateStatusConversationsRequestStatusOpen,
//	}
//	client.Conversations.UpdateStatus(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateStatus(
	ctx context.Context,
	request *sequenzygo.UpdateStatusConversationsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.UpdateStatusConversationsResponse, error) {
	response, err := c.WithRawResponse.UpdateStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
