// Code generated by Fern. DO NOT EDIT.

package lists

import (
	context "context"
	http "net/http"

	sequenzygo "github.com/sequenzy/sequenzy-go"
	core "github.com/sequenzy/sequenzy-go/core"
	internal "github.com/sequenzy/sequenzy-go/internal"
	option "github.com/sequenzy/sequenzy-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) AddSubscribers(
	ctx context.Context,
	request *sequenzygo.AddSubscribersListsRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.AddSubscribersListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/lists/%v/subscribers",
		request.ListID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *sequenzygo.AddSubscribersListsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.AddSubscribersListsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Create(
	ctx context.Context,
	request *sequenzygo.CreateListsRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.CreateListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := baseURL + "/lists"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *sequenzygo.CreateListsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.CreateListsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Delete(
	ctx context.Context,
	request *sequenzygo.DeleteListsRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.DeleteListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/lists/%v",
		request.ListID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *sequenzygo.DeleteListsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.DeleteListsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.ListListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := baseURL + "/lists"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *sequenzygo.ListListsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.ListListsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RemoveSubscribers(
	ctx context.Context,
	request *sequenzygo.RemoveSubscribersListsRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.RemoveSubscribersListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/lists/%v/subscribers/remove",
		request.ListID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *sequenzygo.RemoveSubscribersListsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.RemoveSubscribersListsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Update(
	ctx context.Context,
	request *sequenzygo.UpdateListsRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.UpdateListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/lists/%v",
		request.ListID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *sequenzygo.UpdateListsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.UpdateListsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
