// Code generated by Fern. DO NOT EDIT.

package sendingstatus

import (
	context "context"

	sequenzygo "github.com/sequenzy/sequenzy-go"
	core "github.com/sequenzy/sequenzy-go/core"
	internal "github.com/sequenzy/sequenzy-go/internal"
	option "github.com/sequenzy/sequenzy-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns whether company-level sending is active, paused, or suspended, the pause reason, the sender-health counts and thresholds behind it, the automated review state, whether sending can be restored without support, and ordered remediation steps. Call this whenever a send or test send fails for a reason that is not a validation error. Enforcement uses all-time totals from a reset watermark rather than a rolling window, so metricsWindow.expiresAt is always null and waiting does not restore sending. Requires the account:read scope.
//
// Example:
//
//	client.SendingStatus.Get(
//	    context.TODO(),
//	)
func (c *Client) Get(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sequenzygo.SendingStatus, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Restores company-level sending paused by a high permanent-bounce rate, after the cause has been fixed. This is not a bypass - it enforces the same gates as the dashboard and never removes suppressions. For a paused workspace, sending is restored only when selfResume.canSelfResume is true on GET /sending-status, which requires a high_hard_bounce_rate pause, a cleared automated sender-health review, and no admin block. An already-active workspace succeeds as an idempotent no-op with resumed false. On restoration the bounce watermark moves to now and the service attempts to requeue paused campaigns plus due sequence steps. A partial queue handoff still returns the committed active state with recovery guidance in message. Requires the companies:manage scope plus owner or admin access.
//
// Example:
//
//	request := &sequenzygo.ResumeSendingStatusRequest{
//	    ListSanitizationConfirmed: true,
//	}
//	client.SendingStatus.Resume(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Resume(
	ctx context.Context,
	request *sequenzygo.ResumeSendingStatusRequest,
	opts ...option.RequestOption,
) (*sequenzygo.ResumeSendingStatusResponse, error) {
	response, err := c.WithRawResponse.Resume(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
