// Code generated by Fern. DO NOT EDIT.

package senderprofiles

import (
	context "context"
	http "net/http"

	sequenzygo "github.com/sequenzy/sequenzy-go"
	core "github.com/sequenzy/sequenzy-go/core"
	internal "github.com/sequenzy/sequenzy-go/internal"
	option "github.com/sequenzy/sequenzy-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) Delete(
	ctx context.Context,
	request *sequenzygo.DeleteSenderProfilesRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.DeleteSenderProfilesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sender-profiles/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *sequenzygo.DeleteSenderProfilesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.DeleteSenderProfilesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.ListSenderProfilesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := baseURL + "/sender-profiles"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *sequenzygo.ListSenderProfilesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.ListSenderProfilesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Update(
	ctx context.Context,
	request *sequenzygo.UpdateSenderProfilesRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.UpdateSenderProfilesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sender-profiles/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *sequenzygo.UpdateSenderProfilesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.UpdateSenderProfilesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateReplyProfile(
	ctx context.Context,
	request *sequenzygo.UpdateReplyProfileRequest,
	opts ...option.RequestOption,
) (*core.Response[*sequenzygo.UpdateReplyProfileResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sequenzy.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/reply-profiles/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *sequenzygo.UpdateReplyProfileResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sequenzygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sequenzygo.UpdateReplyProfileResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
