// Code generated by Fern. DO NOT EDIT.

package suppressions

import (
	context "context"

	sequenzygo "github.com/sequenzy/sequenzy-go"
	core "github.com/sequenzy/sequenzy-go/core"
	internal "github.com/sequenzy/sequenzy-go/internal"
	option "github.com/sequenzy/sequenzy-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Checks one exact recipient against Sequenzy's local bounce and complaint safeguards and the regional Amazon SES account-level suppression list. The lookup does not expose unrelated recipients from the shared SES account.
//
// Example:
//
//	request := &sequenzygo.GetSuppressionsRequest{
//	    Email: "email",
//	    Region: sequenzygo.String(
//	        "us-east-1",
//	    ),
//	}
//	client.Suppressions.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *sequenzygo.GetSuppressionsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.GetSuppressionsResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Lists the recipients this company cannot reach, newest suppression first by default.
//
// Four product-level suppression types appear:
//
// - `suppressionType: invalid_recipient` - SMTP evidence conclusively identifies an invalid destination. It is global, visible to companies associated with the address, and protected.
// - `suppressionType: unknown_hard_bounce` - a permanent/undetermined failure without enough evidence to declare the inbox invalid. It is company-scoped and protected.
// - `suppressionType: soft_bounce_escalation` - repeated delivery failures from this company. It is company-scoped and removable.
// - `suppressionType: complaint` - the recipient reported this company's email as spam. It is company-scoped and protected.
//
// The platform-wide list is never exposed: a global row is returned only when the address is already associated with the authenticated company.
//
// Example:
//
//	request := &sequenzygo.ListSuppressionsRequest{}
//	client.Suppressions.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *sequenzygo.ListSuppressionsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.ListSuppressionsResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Removes one company-associated recipient's workspace-scoped soft-bounce escalation and reactivates a bounced company subscriber. Global invalid-recipient and Amazon SES account-level suppressions, other companies' scoped rows, complaints, and unsubscribes are protected.
//
// Example:
//
//	request := &sequenzygo.RemoveSuppressionsRequest{
//	    Email: "email",
//	    Region: sequenzygo.String(
//	        "us-east-1",
//	    ),
//	}
//	client.Suppressions.Remove(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Remove(
	ctx context.Context,
	request *sequenzygo.RemoveSuppressionsRequest,
	opts ...option.RequestOption,
) (*sequenzygo.RemoveSuppressionsResponse, error) {
	response, err := c.WithRawResponse.Remove(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
